config/routes.rb
Rails.application.routes.draw do
  resources :uutiset

  resources :results

  resources :event_attributes, except: [:index, :show, :new]

  resources :events
  
  resources :users
  resources :sessions, only: [:new, :create]
  resources :enrollments, only: [:create, :index]
  resources :groups, only: [:new, :create, :show]
  resources :relay_groups, only: [:new, :create, :show]
  resources :kk_enrollments, only: [:show, :update, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'enrollments/:enrollment_id/edit', to: 'enrollments#edit', as: 'edit_enrollment'
  get 'enrollments/outsider/:event_id', to:'enrollments#new_outsider_enrollment', as: 'outsider_enrollment'
  post 'enrollments/outsider/:event_id', to: 'enrollments#create_outsider_enrollment', as: 'create_outsider_enrollment'
  get 'results/year/:year/:gender/:age_group/:type', to: 'results#index_by_year', as: 'index_by_year'

  get 'uutiset/arkisto/:year', to: 'uutiset#archive_by_year', as: 'archive_by_year'

  get 'admin/kk_enrollment', to: 'static_pages#kk_enrollment'
  get 'admin/cover_image', to: 'static_pages#cover_image'
  post 'admin/change_cover_image', to: 'static_pages#change_cover_image'
  get 'admin/import_payments', to: 'static_pages#import_payments'
  put 'admin/import_payments_file', to: 'static_pages#import_payments_file', as: 'import_payments_file'
  get 'admin/list_years_awards', to: 'yearly_awards#list_years_awards', as: 'years_awards'
  get 'kk_enrollments', to: 'kk_enrollments#index'
  delete 'kk_enrollments/:id', to: 'kk_enrollments#destroy'
  post 'kk_enrollment/change', to: 'kk_enrollments#change_enrollment_status'
  get 'users/:id/kk_enrollments/new', to: 'kk_enrollments#new', as: 'new_kk_enrollment'
  post 'users/:id/kk_enrollments/new', to: 'kk_enrollments#create'

  root 'static_pages#etusivu3'
  get 'static_pages/etusivu3'

  get 'esittely/kalevankierros', to: 'static_pages#kalevankierros'
  get 'esittely/lajikuvaukset', to: 'static_pages#lajikuvaukset'
  get '/ilmoittautuminen', to: 'static_pages#ilmoittautuminen', as: 'ilmoittautuminen'
  get 'esittely/pistelasku', to: 'static_pages#pistelasku'
  get 'esittely/saannot', to: 'static_pages#saannot'
  get 'esittely/hallituksen-kokoukset', to: 'static_pages#hallituksen-kokoukset'

  get 'yhteystiedot', to: 'static_pages#yhteystiedot'
  get 'yhteystiedot/palaute', to: 'static_pages#palaute'
  get 'yhteystiedot/hallitus', to: 'static_pages#hallitus'
  get 'yhteystiedot/seurat', to: 'static_pages#seurat'
  get 'yhteystiedot/linkkeja', to: 'static_pages#linkkeja'
  get 'yhteystiedot/postituslista', to: 'static_pages#postituslista'
  get 'testi', to: 'static_pages#etusivu'
  get '2016', to: 'static_pages#etusivu2'

  get 'haastekisa', to: 'static_pages#haastekisa'

  get 'diplomas', to: 'printing_materials#export_diplomas', as: 'export_diplomas'
  get 'address_stickers', to: 'printing_materials#export_address_stickers', as: 'export_address_stickers'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'events/:event_id/event_attributes/new', to: 'event_attributes#new', as: 'add_event_attribute'
  post 'events/:event_id/event_attributes/:id', to: 'event_attributes#remove', as: 'remove_event_attribute'
  get 'events/:event_id/enrollments/new', to: 'enrollments#new', as: 'add_enrollment'
  get 'enrollments/:enrollment_id', to: 'enrollments#show', as: 'enrollment'
  delete 'enrollments/:enrollment_id', to: 'enrollments#destroy', as: 'delete_enrollment'
  get 'groups/:id/add_user', to: 'groups#add_user_to_group', as: 'add_user_to_group'
  post 'groups/:id/add_user', to: 'groups#update_user_group_relation'
  put 'groups/:id', to: 'groups#delete_user_from_group', as: 'delete_user_from_group'
  get 'relay_groups', to: 'relay_groups#index'
  get 'relay_groups/:id/add_user', to: 'relay_groups#add_user_to_relay_group', as: 'add_user_to_relay_group'
  post 'relay_groups/:id/add_user', to: 'relay_groups#update_user_relay_group_relation'
  put 'relay_groups/:id', to: 'relay_groups#delete_user_from_relay_group', as: 'delete_user_from_relay_group'
  get 'event_enrollments/:event_id/', to: 'enrollments#show_enrollments_for_event', as: 'show_enrollments'
  put 'event_enrollments/', to:'enrollments#update', as: 'add_times_and_payment_info'
  put 'kk_enrollments/', to:'kk_enrollments#update', as: 'add_payment_info'
  put 'relay_groups/', to:'relay_groups#update', as: 'add_relay_payment_info'
  get 'event_enrollments/:event_id/single', to: 'enrollments#single'
  post 'event_enrollments/:event_id/single', to: 'enrollments#update_single'
  put 'event_enrollments/:event_id/import_csv', to: 'enrollments#import_csv', as: 'import_file'
  post 'event_enrollments/:event_id/remove_all_payment_info_for_event', to: 'enrollments#remove_all_payment_info_for_event', as: 'cancel_payments'
  put 'enrollments/:enrollment_id', to: 'enrollments#delete_time', as: 'delete_time'
  put 'enrollments/:enrollment_id/payment', to: 'enrollments#update_payment_info', as: 'update_payment_info'
  post 'results/:event_id', to: 'results#calculate_points', as: 'calculate_points'
  patch 'enrollment_datas/:id', to: 'enrollment_datas#update', as: 'enrollment_datum'
  get 'results/year/:year/groups', to: 'results#with_existing_group', as: 'results_by_year_and_groups'
  get 'results/groups/female_groups', to: 'results#with_female_group', as: 'results_for_female_groups'
  get 'results/groups/mixed_groups', to: 'results#with_mixed_group', as: 'results_for_mixed_groups'
  get 'results/year/:year/relay_groups', to: 'results#with_existing_relay_group', as: 'results_by_year_and_relay_groups'
  get 'results/xlsx/participants_for_year_book', to: 'results#xlsx_results_for_year_book', as: 'individual_results_to_year_book'
  get 'results/individual/series', to: 'results#top_results_for_different_series', as: 'top_series_results'
  get 'users/:id/activate', to: 'users#new_activation', as: 'activation'
  put 'users/:id/activate', to: 'users#activate'
  get 'statistics', to: 'statistics#index', as: 'statistics'
  get 'statistics/search', to: 'statistics#index_filterable', as: 'statistics_filterable'
  get 'statistics/static', to: 'statistics#index_static'
  get 'statistics/:id', to: 'statistics#show', as: 'statistic'
  delete 'statistics/:id', to: 'statistics#destroy', as: 'delete_statistic'
  get 'statistics/:id/edit', to: 'statistics#edit', as: 'edit_statistic'
  patch 'statistics/:id', to: 'statistics#update', as: 'update_statistic'
  get 'users/:id/statistic', to: 'statistics#join', as: 'join_statistic'
  put 'users/:id/statistic', to: 'statistics#join_user_to_existing_statistic'
  post 'statistics/update/:year', to: 'statistics#update_statistics', as: 'update_statistics'
  post 'statistics/update', to: 'statistics#update_statistics'
  get '*path' => redirect('/')

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'date'

  before_action :redirect_if_user_not_admin, only: [:kk_enrollment, :cover_image, :change_cover_image, :import_payments, :import_payments_file]

  def home
    @cover_image_path = AppSetting.find_by name: 'cover_image_path'
  end

  def cover_image
    @images = Dir.glob("app/assets/images/*")
  end

  def change_cover_image
    image_info = AppSetting.find_by name: 'cover_image_path'
    image_info.value = params[:image_path][18..-1]
    image_info.save
    redirect_to root_path
  end

  def kk_enrollment
    @years = Result.distinct.pluck :year
    @account_number = AppSetting.find_by name: 'KkAccountNumber'
    @kk_year = AppSetting.find_by name: 'KkYear'
    @deadline = AppSetting.find_by name: 'Enrollment_Deadline'
  end

  def ilmoittautuminen

  end

  def import_payments_file
    file = params[:file]
    if file.nil?
      redirect_to :root, flash: { error: "Ei valittua tiedostoa!" }
      return
    end
    CSV.foreach(file.path, encoding: 'iso-8859-1', headers: true, header_converters: :symbol, col_sep: ";") do |row|
      result_hash = row.to_hash
      if result_hash[:selitys] == "VIITESIIRTO"
        viite = result_hash[:viite].to_s.delete(" ")

        # Relay group payment
        if viite[0..1] == "99" and viite.length == 10
          kk_number = viite[2..8]
          user = User.find_by kk_number: kk_number.to_i
          relay_group = user.relay_group
          if relay_group
	    relay_group.paid = (result_hash[:mr_euroa].tr(',', '.').to_f * 100.0).to_i
            relay_group.value_date = Date::strptime(result_hash[:arvopiv], "%d.%m.%Y")
            relay_group.save
	  end
        else
          kk_number = viite[0..6]
          event_id = viite[7..viite.length-2]
          user = User.find_by kk_number: kk_number.to_i
          if user
            # Event enrollment payment
            if event_id.length > 0
              enrollment_id = user.find_enrollment_id_by_event(event_id)
              if enrollment_id
                enrollment = Enrollment.find enrollment_id
                if enrollment
                  enrollment.paid = (result_hash[:mr_euroa].tr(',', '.').to_f * 100.0).to_i
                  enrollment.value_date = Date::strptime(result_hash[:arvopiv], "%d.%m.%Y")
                  enrollment.save
                end
              end
            # Kk enrollment payment
            else
              kk_enrollment = user.kk_enrollment
              if kk_enrollment
                kk_enrollment.paid = (result_hash[:mr_euroa].tr(',', '.').to_f * 100.0).to_i
                kk_enrollment.value_date = Date::strptime(result_hash[:arvopiv], "%d.%m.%Y")
                kk_enrollment.save
              end
            end
          end
        end
      end
    end
    redirect_to :root, flash: { success: "Makstiedot on luettu onnistuneesti." }
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/cover_image.html.erb
<div class="col-lg-4">

<h1>Kansikuvan vaihto</h1>
<p>Vaihda etusivun kuva valitsemalla kuva valikosta</p>

<%= bootstrap_form_tag url: admin_change_cover_image_path, method: :post do |f| %>
  <%= f.select :image_path, options_for_select(@images), label: 'Kansikuva' %>
  <%= f.submit 'Vaihda kuva' %>
<% end %>
</div>

app/views/static_pages/etusivu.html.erb
</div>
<div class="container etusivu">
    <li><a href="/esittely/kalevankierros">Kalevan kierros</a></li>
    <li><a href="/esittely/lajikuvaukset">Lajikuvaukset</a></li>
    <li><a href="/uutiset">Uutiset</a></li>
    <li><a href="/esittely/pistelasku">Pistelasku</a></li>
    <li><a href="/esittely/saannot">Säännöt</a></li>
    <li><a href="/ilmoittautuminen" id="themes">Ilmoittautuminen kierrokselle</a></li>
    <li><%= link_to 'Ilmoittautuminen tapahtumiin', events_path %></li>
    <li><%= link_to 'Tulokset', results_path %></li>
    <li><a href="/statistics">Tilastot</a></li>
    <li><a href="/haastekisa">Haastekisa</a></li>
    <li><a href="/yhteystiedot/hallitus" >Hallitus</a></li>
    <li><a href="/yhteystiedot/seurat">Seurat</a></li>
    <li><a href="/yhteystiedot/linkkeja">Linkkejä</a></li>
    <li><a href="http://www.kalevankierros.fi/phpbb/index.php">Forum</a></li>

app/views/static_pages/home.html.erb
<div class="cover-image" style="background-image: url('<%= asset_path @cover_image_path.value %>')">
  <div class="container"><img src="<%= asset_path 'KK_pysty_verkko_RGB_nega.png' %>" style="height: 30%; width: 30%; margin-top: -5px;"/></div>
</div>

<div class="container">
  <div class="col-lg-8">
    <h4>Kalevan Kierros on kuuden kestävyyslajin kunto- ja kilpaurheilutapahtuma.
    Kierros motivoi kuntoilijaa säännölliseen liikkumiseen ja koettelee urheilijaa erilaisilla vaatimuksillaan.
    Harjoittelu ei ole yksipuolista, kun kilpailulaji vaihtuu säännöllisesti noin kahden kuukauden välein.</h4>
  </div>
  <div class="col-lg-4" >
    <a href="http://www.facebook.com/KalevanKierros" title="Kalevan Kierros Facebookissa"><h4><%= image_tag 'facebook-icon.png', height: '50'   %> Facebook-ryhmä</h4></a>
    <a href="http://palvelin3.kalevankierros.fi/phpbb" title="Kalevan Kierros - Foorumi"><h4><%= image_tag 'foorumi.png', height: '50'  %> KK-Forum</h4></a>
  </div>
  <div class="col-lg-8">
    <h4>Osakilpailut vuonna 2016</h4>
    <div class="row">
      <div class="col-xs-2"><h5>30.1.</h5></div>
      <div class="col-xs-2"><h5>Luistelu</h5></div>
      <div class="col-xs-2"><h5>30 km</h5></div>
      <div class="col-xs-4"><h5>Oulunkylä, Helsinki</h5></div>
    </div>
    <div class="row">
      <div class="col-xs-2"><h5>19.3.</h5></div>
      <div class="col-xs-2"><h5>Hiihto</h5></div>
      <div class="col-xs-2"><h5>45 km</h5></div>
      <div class="col-xs-4"><h5>Vuokatti, Sotkamo</h5></div>
    </div>
    <div class="row">
      <div class="col-xs-2"><h5>21.5.</h5></div>
      <div class="col-xs-2"><h5>Juoksu</h5></div>
      <div class="col-xs-2"><h5>21.1km/42.2km</h5></div>
      <div class="col-xs-4"><h5>Tuusula</h5></div>
    </div>
    <div class="row">
      <div class="col-xs-2"><h5>2.7.</h5></div>
      <div class="col-xs-2"><h5>Soutu</h5></div>
      <div class="col-xs-2"><h5>30 km</h5></div>
      <div class="col-xs-4"><h5>Keuruu</h5></div>
    </div>
    <div class="row">
      <div class="col-xs-2"><h5>20.8.</h5></div>
      <div class="col-xs-2"><h5>Pyöräily</h5></div>
      <div class="col-xs-2"><h5>70 km</h5></div>
      <div class="col-xs-4"><h5>Iitti</h5></div>
    </div>
    <div class="row">
      <div class="col-xs-2"><h5>25.9.</h5></div>
      <div class="col-xs-2"><h5>Suunnistus</h5></div>
      <div class="col-xs-2"><h5>15 km</h5></div>
      <div class="col-xs-4"><h5>Hämeenkyrö</h5></div>
    </div>

    <h1>
      <% if enrollment_open? %>
        <%= link_to('Ilmoittaudu Kalevan Kierrokselle 2016', ilmoittautuminen_path, :class => "btn btn-primary") %>
      <% end %>
    </h1>
    <h1>_</h1>
  </div>
  <div class="col-lg-4" >
    <%= render :partial => '/uutiset/latest', locals: {show_latest: Uutiset.order('created_at desc').limit(10)} %>
  </div>
  <div class="col-lg-4">
    <%= render_shareable :buttons=> ['twitter', 'facebook'] %>
  </div>
</div>

<div class="container">
  <div class="col-lg-3">
    <a href="http://www.haastaitsesikunnolla.fi/vuokatti+hiihto">
      <img src="<%= asset_path 'VuokattiHiihto_logo.jpg' %>">
    </a>
  </div>
  <div class="col-lg-3">
    <a href="http://www.pwt-urheilumatkat.fi">
      <img src="download/PWTbanneri.JPG">">
    </a>
  </div>
  <div class="col-lg-3">
    <a href="http://tuusulanjarvenmaraton.fi/">
      <img src="download/tjm.png">
    </a>
  </div>
</div>

app/views/static_pages/ilmoittautuminen.html.erb
<div class="col-lg-8">
  <h1>Ilmoittautuminen Kalevan Kierrokselle 2016</h1>

  <p>Kalevan Kierrokselle voi ilmoittautua joko yksilönä tai joukkueena.
  Yksilön maksu 50 euroa, joka koostuu 20 euron jäsenmaksusta ja 30 euron yhteiskilpailumaksusta.
  Joukkueessa voi olla 4-6 jäsentä ja maksu on 200 eur per joukkue. Osanottomaksuun sisältyy
  mitali, diplomi, eri sarjoissa jaettavat palkinnot sekä tapaturmavakuutus, joka käsittää kaikki
  kuusi osakilpailua ja on voimassa kilpailujen aikana sekä välittömillä kilpailumatkoilla.</p>

  <% if enrollment_open? %>
      <% if current_user %>
          <% if current_user.kk_enrollment.nil? %>
            <p>Valitse yksi seuraavista:</p>
            <p>
              <% #button_to('En kuulu joukkueeseen ja ilmoittaudun yksilönä', new_kk_enrollment_path(current_user.id), method: :get) %>
              <%= link_to('En kuulu joukkueeseen ja ilmoittaudun yksilönä', new_kk_enrollment_path(current_user.id), :class => "btn btn-primary" ) %>
            </p>
            <% if current_user.group.nil? and current_user.relay_group.nil? %>
              <p>
                <%= link_to('Olen joukkueen kapteeni ja ilmoitan joukkueen jäsenet', new_group_path(current_user.id), :class => "btn btn-primary") %>
                <% #button_to('Olen joukkueen kapteeni ja ilmoitan joukkueen jäsenet', new_group_path(current_user.id), method: :get) %>
              </p>
              <p>
                <%= link_to('Olen joukkueen jäsen ja kapteeni ilmoittaa minut', user_path(current_user), :class => "btn btn-primary") %>
              </p>
            <% end %>
          <% else %>
              <% if current_user.group.nil? %>
                <%= link_to('Olet jo ilmoittautunut Kalevan Kierrokselle 2016', user_path(current_user), :class => "btn btn-info") %>
              <% else %>
                  <% if current_user.group.user === current_user %>
                      <%= link_to('Ilmoita joukkueen jäseniä', group_path(current_user.group), :class => "btn btn-info") %>
                  <% else %>
                      <%= link_to('Olet jo ilmoittautunut Kalevan Kierrokselle 2016', user_path(current_user), :class => "btn btn-info") %>
                  <% end %>
              <% end %>
          <% end %>
      <% else %>
        <p>Valitse ensin:</p>
        <p>
          <%= link_to('Kirjaudu - Osallistuin Kalevan Kierrokselle 2015 tai olen jo rekisteröitynyt', signin_path(redirect: 'kkenrollment'), :class => "btn btn-info") %>
        </p>
        <p>
          <%= link_to('Rekisteröidy - En osallistunut Kalevan Kierrokselle 2015', signup_path, :class => "btn btn-info") %>
        </p>
      <% end %>

  <% else %>

    <%= link_to('Ilmoittautuminen Kalevan Kierrokselle 2016 on päättynyt', root_path, :class => "btn btn-info") %>

  <% end %>

  <p></br>Jos et halua kilpailla, mutta haluat olla yhdistyksen jäsen, lähetä viestiä Mikolle: <a href="mailto:mikko.p.fagerstrom@elisanet.fi">mikko.p.fagerstrom(at)elisanet.fi</a></p>
  <h3>Osalajit</h3>
  <p>Kalevan Kierroksen osalajeihin ilmoittaudutaan ja maksetaan osallistumismaksut erikseen.
  Osalajien kilpailukutsut ja ilmoittautumisohjeet tulevat Kierroksen sivuille,
  kun osalaji alkaa olla ajankohtainen. Osakilpailuista peritään osallistumismaksu,
  joka on yleensä noin 35 euron suuruinen.</p>

  <% if enrollment_open? %>
    <% if current_user and current_user.group.nil? and current_user.relay_group.nil? %>
      <h1>Ilmoita joukkue viestikilpailuun:</h1>
        <p>
          <%= link_to('Ilmoita viestijoukkue', new_relay_group_path(current_user.id), :class => "btn btn-primary") %>
        </p>
    <% end %>
  <% end %>
</div>

app/views/static_pages/import_payments.html.erb
<div class="col-lg-4">

<h1>Viitemaksujen tuonti</h1>
<p>Lue saapuneet viitemaksut tiedostosta</p>

<%= form_tag import_payments_file_path, multipart:true, method: :put do %>
  <%= file_field_tag :file %>
  <%= submit_tag 'Lähetä tiedosto', :class => "btn btn-primary"  %>
<% end %>

app/views/static_pages/kalevankierros.html.erb
<div class="col-lg-8">
  <h1>Kalevan Kierros</h1>

  <p class="lead">Kalevan Kierros on kuuden kestävyyslajin kunto- ja kilpaurheilutapahtuma. Kierros motivoi kuntoilijaa säännölliseen
  liikkumiseen ja koettelee urheilijaa erilaisilla vaatimuksillaan. Harjoittelu ei ole yksipuolista, kun kilpailulaji
  vaihtuu säännöllisesti noin kahden kuukauden välein.</p>

  <p>Kierros lähtee käyntiin, kun tammi-helmikuun vaihteessa luistellaan 30 kilometriä. Sen jälkeen on noin kuukausi aikaa
  hioa hiihtokunto huippuunsa ja valmistautua 45 km:n rypistykseen. Toukokuun lopulla juostavaan maratoniin tai
  puolimaratoniin ei ole sitten aikaa valmistautua kuin puolitoista kuukautta, joten aika kannattaa käyttää tarkoin
  hyödyksi. Kesä-heinäkuun vaihteessa soudettava 30 kilometriä on aina yhtä kova ja palkitseva urakka, jonka jälkeen
  saakin polkea kauneimman kesän ajan pyörää, valmistautuessaan elokuun puolivälin tienoilla ajettavaan 65 kilometrin
  pyöräilykisaan. Pyöräilyn jälkeen on taas seitsemän viikkoa aikaa valmistautua n. 15 kilometrin suunnistukseen, mutta
  rasteilla on ollut syytä käydä jo keväästä alkaen!</p>


  <h2>TULE JA IHASTU KALEVAN KIERROKSEEN !</h2>

</div>

app/views/static_pages/kk_enrollment.html.erb
<h1>Kierroksen hallinta</h1>
<p>Voit hallita kierrosilmoittautumista täältä. Mikäli ilmoittautuminen ei ole avoinna, eivät kiertäjät pääse ilmoittautumaan kierrokselle. </p>
<% if enrollment_open? %>
  Vuosi: <%= @kk_year.value %><br>
  Kierroksen tilinumero: <%= @account_number.value %>
  Jäsenen joukkueen lisäämisen deadline: <%= Date.parse(@deadline.value).to_s %>
  <%= button_to('Sulje ilmoittautuminen', kk_enrollment_change_path, :class => "btn btn-danger") %>
<% else %>
  <%= form_tag kk_enrollment_change_path do%>
  <%= label_tag :kk_year, 'Vuosi (vaaditaan)' %><br>
  <%= number_field_tag :kk_year, Date.today.year %><br>
  <%= label_tag :account_number, 'Kierroksen tilinumero IBAN-muodossa (vaaditaan)' %>
  <%= text_field_tag :account_number %><br>
  <%= label_tag :group_deadline, 'Jäsenen lisääminen joukkueeseen deadline. (vaaditaan)' %>
  <%= select_date Date.today, prefix: :deadline %><br>
  <%= submit_tag 'Avaa ilmoittautuminen', :class => 'btn btn-success' %>
  <% end %>
<% end %>
<br>
<%= button_to('Näytä ilmoittautumiset', kk_enrollments_path, method: :get, :class => "btn btn-primary") %>
<br>
<%= button_to('Näytä viestijoukkueet', relay_groups_path, method: :get, :class => "btn btn-primary") %>
<br>
<b>Lataa kunniakirjat</b>
<p>Huom. kunniakirjat voi ladata vasta kun suunnistustapahtuma on luotu. Muista tarkistaa nimien oikeinkirjoitus ja tiedostoformaatin oikeellisuus. Kunniakirjoihin tulostuvien tapahtumien nimet on vaihdettavissa nimeämällä itse tapahtuma uudelleen.</p>
<%= button_to('Lataa', export_diplomas_path, method: :get, :class => "btn btn-primary") %>

<br>
<b>Lataa osoitetarrat ilmoittautuneille kiertäjille.</b>
<%= button_to('Lataa', export_address_stickers_path, method: :get, :class => "btn btn-primary") %>

<br>
<b>Listaa vuoden ansiomerkit</b>
<p>Ansiomerkkilistaus on ladattavissa koko vuoden ajan. Lopullinen versio on saatavilla kun viimeinen osakilpailu on pisteytetty, jolloin myös vuoden kehittyjät listataan.</p>
<%= button_to('Avaa lista', years_awards_path, method: :get, :class => "btn btn-primary") %>

<br>
<b>Lataa henkilökohtaiset tulokset vuosikirjaan</b><br>
<%= button_to('Lataa kaikki tulokset', individual_results_to_year_book_path, params: {format: :xlsx, gender: "kaikki"}, method: :get, :class => "btn btn-primary") %><br>
<%= button_to('Lataa naisten tulokset', individual_results_to_year_book_path, params: {format: :xlsx, gender: "naiset"}, method: :get, :class => "btn btn-primary") %>

<br>
<b>Lataa kaikki henkilökohtaiset tulokset valitulle vuodelle</b><br>
<%= form_tag(individual_results_to_year_book_path, {method: :get}) do %>
  <%= label_tag :year, 'Vuosi:' %><br>
  <%= number_field_tag :year, Date.today.year %><br>
  <%= label_tag :gender, 'Rajaa sukupuolen mukaan:' %><br>
  <%= select_tag :gender, options_for_select(["kaikki", "naiset"]) %><br>
  <%= hidden_field_tag :format, :xlsx %>
  <%= submit_tag('Lataa tulokset', :class => "btn btn-primary") %>
<% end %>

<br>
<b>Lataa joukkuetulokset</b><br>
<%= button_to('Lataa sekajoukkuetulokset', results_for_mixed_groups_path(format: :xlsx), method: :get, :class => "btn btn-primary") %><br>
<%= button_to('Lataa naisten joukkuetulokset', results_for_female_groups_path(format: :xlsx), method: :get, :class => "btn btn-primary") %>

<br>
<b>Lataa sarjakohtaiset kärkitulokset</b><br>
<%= button_to('Lataa', top_series_results_path, method: :get, :class => "btn btn-primary") %><br>

<br>
<b>Päivitä tulosten tiedot tilastoihin</b>
<p><b>Huom. kunniakirjat ja ansiomerkkilistaukset tulee ladata ja tarkistaa ennen vuoden tulosten vientiä tilastoihin.</b></p>
<p>Uudet ansiomerkit tulee päivittää saajille käsin.</p>
<%= bootstrap_form_tag url: statistics_update_path, method: :post do |f| %>
  <%= f.select :year, options_for_select(@years), label: 'Vuosi' %>
  <%= f.submit 'Päivitä tilastot', onclick: "return confirm('Päivitetäänkö tilastot?')" %>
<% end %>

app/views/static_pages/yhteystiedot.html.erb
<div class="col-lg-4">
  <div class="bs-component">
    <h1>Yhteystiedot</h1>

    <p>yhteystiedot</p>
  </div>
</div>