config/routes.rb
Rails.application.routes.draw do
  resources :uutiset

  resources :results

  resources :event_attributes, except: [:index, :show, :new]

  resources :events
  
  resources :users
  resources :sessions, only: [:new, :create]
  resources :enrollments, only: [:create, :index]
  resources :groups, only: [:new, :create, :show]
  resources :relay_groups, only: [:new, :create, :show]
  resources :kk_enrollments, only: [:show, :update, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'enrollments/:enrollment_id/edit', to: 'enrollments#edit', as: 'edit_enrollment'
  get 'enrollments/outsider/:event_id', to:'enrollments#new_outsider_enrollment', as: 'outsider_enrollment'
  post 'enrollments/outsider/:event_id', to: 'enrollments#create_outsider_enrollment', as: 'create_outsider_enrollment'
  get 'results/year/:year/:gender/:age_group/:type', to: 'results#index_by_year', as: 'index_by_year'

  get 'uutiset/arkisto/:year', to: 'uutiset#archive_by_year', as: 'archive_by_year'

  get 'admin/kk_enrollment', to: 'static_pages#kk_enrollment'
  get 'admin/cover_image', to: 'static_pages#cover_image'
  post 'admin/change_cover_image', to: 'static_pages#change_cover_image'
  get 'admin/import_payments', to: 'static_pages#import_payments'
  put 'admin/import_payments_file', to: 'static_pages#import_payments_file', as: 'import_payments_file'
  get 'admin/list_years_awards', to: 'yearly_awards#list_years_awards', as: 'years_awards'
  get 'kk_enrollments', to: 'kk_enrollments#index'
  delete 'kk_enrollments/:id', to: 'kk_enrollments#destroy'
  post 'kk_enrollment/change', to: 'kk_enrollments#change_enrollment_status'
  get 'users/:id/kk_enrollments/new', to: 'kk_enrollments#new', as: 'new_kk_enrollment'
  post 'users/:id/kk_enrollments/new', to: 'kk_enrollments#create'

  root 'static_pages#etusivu3'
  get 'static_pages/etusivu3'

  get 'esittely/kalevankierros', to: 'static_pages#kalevankierros'
  get 'esittely/lajikuvaukset', to: 'static_pages#lajikuvaukset'
  get '/ilmoittautuminen', to: 'static_pages#ilmoittautuminen', as: 'ilmoittautuminen'
  get 'esittely/pistelasku', to: 'static_pages#pistelasku'
  get 'esittely/saannot', to: 'static_pages#saannot'
  get 'esittely/hallituksen-kokoukset', to: 'static_pages#hallituksen-kokoukset'

  get 'yhteystiedot', to: 'static_pages#yhteystiedot'
  get 'yhteystiedot/palaute', to: 'static_pages#palaute'
  get 'yhteystiedot/hallitus', to: 'static_pages#hallitus'
  get 'yhteystiedot/seurat', to: 'static_pages#seurat'
  get 'yhteystiedot/linkkeja', to: 'static_pages#linkkeja'
  get 'yhteystiedot/postituslista', to: 'static_pages#postituslista'
  get 'testi', to: 'static_pages#etusivu'
  get '2016', to: 'static_pages#etusivu2'

  get 'haastekisa', to: 'static_pages#haastekisa'

  get 'diplomas', to: 'printing_materials#export_diplomas', as: 'export_diplomas'
  get 'address_stickers', to: 'printing_materials#export_address_stickers', as: 'export_address_stickers'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'events/:event_id/event_attributes/new', to: 'event_attributes#new', as: 'add_event_attribute'
  post 'events/:event_id/event_attributes/:id', to: 'event_attributes#remove', as: 'remove_event_attribute'
  get 'events/:event_id/enrollments/new', to: 'enrollments#new', as: 'add_enrollment'
  get 'enrollments/:enrollment_id', to: 'enrollments#show', as: 'enrollment'
  delete 'enrollments/:enrollment_id', to: 'enrollments#destroy', as: 'delete_enrollment'
  get 'groups/:id/add_user', to: 'groups#add_user_to_group', as: 'add_user_to_group'
  post 'groups/:id/add_user', to: 'groups#update_user_group_relation'
  put 'groups/:id', to: 'groups#delete_user_from_group', as: 'delete_user_from_group'
  get 'relay_groups', to: 'relay_groups#index'
  get 'relay_groups/:id/add_user', to: 'relay_groups#add_user_to_relay_group', as: 'add_user_to_relay_group'
  post 'relay_groups/:id/add_user', to: 'relay_groups#update_user_relay_group_relation'
  put 'relay_groups/:id', to: 'relay_groups#delete_user_from_relay_group', as: 'delete_user_from_relay_group'
  get 'event_enrollments/:event_id/', to: 'enrollments#show_enrollments_for_event', as: 'show_enrollments'
  put 'event_enrollments/', to:'enrollments#update', as: 'add_times_and_payment_info'
  put 'kk_enrollments/', to:'kk_enrollments#update', as: 'add_payment_info'
  put 'relay_groups/', to:'relay_groups#update', as: 'add_relay_payment_info'
  get 'event_enrollments/:event_id/single', to: 'enrollments#single'
  post 'event_enrollments/:event_id/single', to: 'enrollments#update_single'
  put 'event_enrollments/:event_id/import_csv', to: 'enrollments#import_csv', as: 'import_file'
  post 'event_enrollments/:event_id/remove_all_payment_info_for_event', to: 'enrollments#remove_all_payment_info_for_event', as: 'cancel_payments'
  put 'enrollments/:enrollment_id', to: 'enrollments#delete_time', as: 'delete_time'
  put 'enrollments/:enrollment_id/payment', to: 'enrollments#update_payment_info', as: 'update_payment_info'
  post 'results/:event_id', to: 'results#calculate_points', as: 'calculate_points'
  patch 'enrollment_datas/:id', to: 'enrollment_datas#update', as: 'enrollment_datum'
  get 'results/year/:year/groups', to: 'results#with_existing_group', as: 'results_by_year_and_groups'
  get 'results/groups/female_groups', to: 'results#with_female_group', as: 'results_for_female_groups'
  get 'results/groups/mixed_groups', to: 'results#with_mixed_group', as: 'results_for_mixed_groups'
  get 'results/year/:year/relay_groups', to: 'results#with_existing_relay_group', as: 'results_by_year_and_relay_groups'
  get 'results/xlsx/participants_for_year_book', to: 'results#xlsx_results_for_year_book', as: 'individual_results_to_year_book'
  get 'results/individual/series', to: 'results#top_results_for_different_series', as: 'top_series_results'
  get 'users/:id/activate', to: 'users#new_activation', as: 'activation'
  put 'users/:id/activate', to: 'users#activate'
  get 'statistics', to: 'statistics#index', as: 'statistics'
  get 'statistics/search', to: 'statistics#index_filterable', as: 'statistics_filterable'
  get 'statistics/static', to: 'statistics#index_static'
  get 'statistics/:id', to: 'statistics#show', as: 'statistic'
  delete 'statistics/:id', to: 'statistics#destroy', as: 'delete_statistic'
  get 'statistics/:id/edit', to: 'statistics#edit', as: 'edit_statistic'
  patch 'statistics/:id', to: 'statistics#update', as: 'update_statistic'
  get 'users/:id/statistic', to: 'statistics#join', as: 'join_statistic'
  put 'users/:id/statistic', to: 'statistics#join_user_to_existing_statistic'
  post 'statistics/update/:year', to: 'statistics#update_statistics', as: 'update_statistics'
  post 'statistics/update', to: 'statistics#update_statistics'
  get '*path' => redirect('/')

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :enrollments, dependent: :destroy
  has_many :events, through: :enrollments
  has_one :kk_enrollment, dependent: :destroy
  has_one :statistic
  belongs_to :group
  belongs_to :relay_group

  validates :username, uniqueness: true, length: { minimum: 3 }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :birth_date, presence: true
  validates :password, presence: true
  validates :password, length: { minimum: 6 },
                       format: { with: /.*(\d.*[A-Z]|[A-Z].*\d).*/}
  validates :postal_code, format: { with: /\A\d{5}\z/ }
  validates :street_address, presence: true
  validates :city, presence: true

  def get_enrollment_data_for_event(id)
    enrollment = enrollments.find_by event_id: id
    if enrollment
      enrollment.enrollment_datas.where.not(attribute_index: nil).order('attribute_index asc')
    else
      return EnrollmentData.none
    end
  end

  def get_formatted_enrollment_data_for_event(id)
    event = Event.find(id)
    enrollment = enrollments.find_by event_id: id

    if event && enrollment
      data = enrollment.enrollment_datas.where.not(attribute_index: nil).order('attribute_index asc')
      formatted_data = []
      i = 0
      data.each do |d|
        if d.attribute_index > i + 1
          missing = d.attribute_index - i - 1
          missing.times do
            if not event.event_attributes.find_by(attribute_index: i + 1).removed
              formatted_data.append ''
            end
            i += 1
          end
        end

        i += 1
	if not event.event_attributes.find_by(attribute_index: d.attribute_index).removed
          formatted_data.append d.value
        end
      end
      event = Event.find(id)
      last = event.event_attributes.where.not(attribute_index: nil).order('attribute_index asc').last
      if last
        missing = last.attribute_index - i
        missing.times do
          formatted_data.append ''
        end
      end
      formatted_data
    else
      return EnrollmentData.none
    end
  end

  def find_enrollment_id_by_event(id)
    id = enrollments.find_by(event_id: id)
    if id
      id.id
    else
      nil
    end
  end

  def address
    street_address + ' ' + postal_code + ', ' + city
  end

  def full_name
    first_name + ' ' + last_name
  end

  def define_series
    year = AppSetting.find_by(name: 'KkYear').value.to_i
    age = year - birth_date.year
    str = gender
    if age < 22
      str += 'AL22'
    elsif age < 40

    elsif age < 50
      str += '40'
    elsif age < 55
      str += '50'
    elsif age < 60
      str += '55'
    elsif age < 65
      str += '60'
    elsif age < 70
      str += '65'
    elsif age < 75
      str += '70'
    elsif age < 80
      str += '75'
    else
      str += '80'
    end
    str
  end

  def generate_activation_token
    self.activation_token = SecureRandom.urlsafe_base64
  end

  def generate_reset_token
    self.update_attribute :reset_token, SecureRandom.urlsafe_base64
  end

  def set_reset_time
    self.update_attribute :reset_sent_at, DateTime.now
  end

  def construct_reference_number
    number = (kk_number.to_s).split ''
    if number.count < 7 || number.count > 7
      return 'virhe viitenumerossa'
    end
    number.reverse!
    sum = 0
    sum = sum + number[0].to_i * 7
    sum = sum + number[1].to_i * 3
    sum = sum + number[2].to_i * 1
    sum = sum + number[3].to_i * 7
    sum = sum + number[4].to_i * 3
    sum = sum + number[5].to_i * 1
    sum = sum + number[6].to_i * 7
    next_ten = (sum / 10).round * 10 + 10
    check_sum = next_ten - sum
    if check_sum == 10
      check_sum = 0
    end
    return kk_number.to_s.concat(check_sum.to_s)
  end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_user_not_admin, only: [:index, :destroy]
  before_action :set_user_or_redirect, only:  [:show, :edit, :update, :destroy]

  def index
    @userInfo = []

    users = User.all
    potential_statistics = Statistic.where 'statistics.user_id IS NULL'
    users.each do |u|
      current_statistic = u.statistic
      if current_statistic
        first_name = u.first_name.strip.downcase
        last_name = u.last_name.strip.downcase
        birth_year = current_statistic.birth_year
        found = potential_statistics.select do |s|
          s.first_name.strip.downcase.eql?(first_name) && s.last_name.strip.downcase.eql?(last_name) && s.birth_year == birth_year
        end
        joinable = (found.length > 0 and u.username[0..7] != 'outsider') ? 'K' : ''
      else
        joinable = ''
      end
      @userInfo << [u, joinable]
    end
  end

  # GET /users/1
  def show
    @enrollments = @user.enrollments
    @group = @user.group
    @relay_group = @user.relay_group
    @kk_enrollment = @user.kk_enrollment
    year = AppSetting.find_by name: 'KkYear'
    @year = ''
    if year
      @year = year.value
    end
    account = AppSetting.find_by name:'KkAccountNumber'
    @account_number = ''
    if account
      @account_number = account.value
    else
      @account_number = 'Tilinumeroa ei löytynyt'
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    @user.generate_activation_token
    if not session.nil? and not session[:redirect_url].nil?
      redirect_url = session[:redirect_url]
    end
    if @user.save
      UserMailer.registration_activation_email(@user, redirect_url).deliver
      redirect_to signin_path, flash: { success: 'Käyttäjätunnus luotu, aktivoi tunnus sähköpostiin lähetettyjen ohjeiden mukaan.' }
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, flash: { success: 'Käyttäjätiedot päivitetty onnistuneesti.' }
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    message = {}

    if @user != current_user
      @user.destroy
      message = { success: 'Käyttäjä poistettu onnistuneesti.' }
    end

    redirect_to users_url, flash: message
  end

  def new_activation
    @user = User.find_by id: params[:id]
    session[:redirect_url] = params[:redirect_url]
    if !current_user and @user and !@user.active and @user.activation_token == params[:activation_token]
      render :activate and return
    elsif current_user and @user and @user.active and not params[:redirect_url].nil?
      redirect_to params[:redirect_url]
    elsif current_user and @user and @user.active
      redirect_to user_path(current_user)
    else
      redirect_to signin_path
    end
  end

  def activate
    if !current_user
      @user = User.find_by id: params[:id]
      if @user && !@user.active
        if @user.username == params[:username] && (@user.authenticate params[:password])
          if @user.activation_token == params[:activation_token]
            @user.update_attribute(:active, true)
            @user.update_attribute :kk_number, generate_kk_number(@user)
            init_statistic_entry @user
            session[:user_id] = @user.id
            flash[:success] = "Tervetuloa " + @user.first_name
          end
        else
          flash[:error] = "Tarkista käyttäjätunnus ja salasana!"
          redirect_back(fallback_location: root_path) && return
        end
      end
    end
    if not session.nil? and not session[:redirect_url].nil?
      redirect_to session[:redirect_url], flash: { success: 'Käyttäjä aktivoitu' }
    else
      redirect_to user_path(current_user), flash: { success: 'Käyttäjä aktivoitu' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_or_redirect
      if current_user
          @user = User.find_by id: params[:id]
          return if @user && (current_user.id == @user.id || user_is_admin?)
      end

      redirect_to :root
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :email, :phone_number, :city, :street_address, :postal_code, :birth_date, :gender, :password, :password_confirmation)
    end

    def init_statistic_entry(user)
      Statistic.create kk_number: user.kk_number, user_id: user.id,
                       last_name: user.last_name, first_name: user.first_name,
                       city: user.city, birth_year: user.birth_date.year,
                       prev_year_pts_sum: 0.0, prev_year_event_sum: 0,
                       six_events_completed_count: 0, five_events_completed_count: 0,
                       four_events_completed_count: 0, total_events_completed: 0,
                       pts_sum: 0, position: 0, p: nil, a: 0, ap: nil, k: 0, v: 0
    end

    def generate_kk_number(user)
      3300000+user.id
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/activate.html.erb
<div class="col-md-8">
  <div class="bs-component">
    <h2>Aktivoi tili kirjautumalla sisään</h2>

    <%= bootstrap_form_tag url: activation_path, method: :put do |f| %>
	<%= f.text_field :username, label: "Käyttäjätunnus: " %>
        <%= f.password_field :password, label: "Salasana: " %>
        <%= f.hidden_field :activation_token, value: @user.activation_token %>
        <h1><%= f.submit "Kirjaudu sisään", :class => 'btn btn-primary' %></h1>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="col-md-8">
  <h2>Muokkaa tietojasi</h2>
  <h4>Kk-numerosi: <%= @user.kk_number %></h4>

<%= render 'form', :subpage => 'edit' %>
  <h1><a href="http://tiedot.kalevankierros.fi/" class="btn btn-default">Omat tiedot</a></h1>
</div>

app/views/users/index.html.erb
<div class="col-lg-12">
  <h1>Rekisteröityneet käyttäjät</h1>

      <div class="ts-pager form-horizontal">
        <button type="button" class="btn first"><i class="icon-step-backward glyphicon glyphicon-step-backward"></i></button>
        <button type="button" class="btn prev"><i class="icon-arrow-left glyphicon glyphicon-backward"></i></button>
        <span class="pagedisplay"></span> <!-- this can be any element, including an input -->
        <button type="button" class="btn next"><i class="icon-arrow-right glyphicon glyphicon-forward"></i></button>
        <button type="button" class="btn last"><i class="icon-step-forward glyphicon glyphicon-step-forward"></i></button>
        Näytä: <select class="pagesize input-mini form-control" title="Select page size">
        <option selected="selected" value="50">50</option>
        <option value="100">100</option>
      </select>
        Sivu: <select class="pagenum input-mini form-control " title="Select page number"></select>
</div>
  <br/>
  <table id="users" class="table table-striped tablesorter-bootstrap">
    <thead>
    <tr>
      <th>Sukunimi</th>
      <th>Etunimi</th>
      <th>Käyttäjänimi</th>
      <th>Sähköposti</th>
      <th>Liitettävissä tilastoon</th>
      <th></th>
    </tr>
    </thead>
    <tfoot>
      <th>Sukunimi</th>
      <th>Etunimi</th>
      <th>Käyttäjänimi</th>
      <th>Sähköposti</th>
      <th>Liitettävissä tilastoon</th>
      <th></th>
    </tfoot>

    <tbody>
    <% @userInfo.each do |user, joinable| %>
        <tr>
          <td><%= user.last_name %></td>
          <td><%= user.first_name %></td>
          <td><%= user.username %></td>
          <td><%= user.email %></td>
          <td><%= joinable %></td>
          <td style="min-width: 350px; text-align: center;"><%= link_to 'Näytä', user, class: "btn btn-primary btn-sm" %>
          <%= link_to 'Liitä tilastoon', join_statistic_path(user), :'data-no-turbolink' => true, class: "btn btn-primary btn-sm" %>
          <%= link_to 'Muokkaa', edit_user_path(user), class: "btn btn-warning btn-sm" %>
          <% if current_user != user %>
            <%= link_to 'Poista', user, method: :delete, data: {confirm: 'Are you sure?' }, id: "delete#{user.id}", class: "btn btn-danger btn-sm" %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
<br/>
  <div class="ts-pager form-horizontal">
    <button type="button" class="btn first"><i class="icon-step-backward glyphicon glyphicon-step-backward"></i></button>
    <button type="button" class="btn prev"><i class="icon-arrow-left glyphicon glyphicon-backward"></i></button>
    <span class="pagedisplay"></span> <!-- this can be any element, including an input -->
    <button type="button" class="btn next"><i class="icon-arrow-right glyphicon glyphicon-forward"></i></button>
    <button type="button" class="btn last"><i class="icon-step-forward glyphicon glyphicon-step-forward"></i></button>
    Näytä: <select class="pagesize input-mini form-control" title="Select page size">
    <option selected="selected" value="50">50</option>
    <option value="100">100</option>
  </select>
    Sivu: <select class="pagenum input-mini form-control " title="Select page number"></select>
  </div>
  <style type="text/css">
    select.form-control{
      max-width: 70px;
      display: inline;
    }
    @media (min-width: 992px) {
      .container {
        width: 100% !important;
      }
    }
  </style>

            <script type="text/javascript">

                $(document).ready(function () {
                            $.extend($.tablesorter.themes.bootstrap, {
                                // these classes are added to the table. To see other table classes available,
                                // look here: http://twitter.github.com/bootstrap/base-css.html#tables
                                table      : 'table table-bordered',
                                caption    : 'caption',
                                header     : 'bootstrap-header', // give the header a gradient background
                                footerRow  : '',
                                footerCells: '',
                                icons      : '', // add "icon-white" to make them white; this icon class is added to the <i> in the header
                                sortNone   : 'bootstrap-icon-unsorted',
                                sortAsc    : 'icon-chevron-up glyphicon glyphicon-chevron-up',     // includes classes for Bootstrap v2 & v3
                                sortDesc   : 'icon-chevron-down glyphicon glyphicon-chevron-down', // includes classes for Bootstrap v2 & v3
                                active     : '', // applied when column is sorted
                                hover      : '', // use custom css here - bootstrap class may not override it
                                filterRow  : '', // filter row class
                                even       : '', // odd row zebra striping
                                odd        : ''  // even row zebra striping
                            });

                            $("#users").tablesorter({
                                headers: {5: {sorter:false, filter:false} },
                                theme : "bootstrap",
                                headerTemplate : '{content} {icon}',
                                widgets : [ "uitheme", "filter" ]
                            })
                                    .tablesorterPager({

                                        // target the pager markup - see the HTML block below
                                        container: $(".ts-pager"),
                                        size: 50,

                                        // target the pager page select dropdown - choose a page
                                        cssGoto: ".pagenum",

                                        // remove rows from the table to speed up the sort of large tables.
                                        // setting this to false, only hides the non-visible rows; needed if you plan to add/remove rows with the pager enabled.
                                        removeRows: false,

                                        // output string - default is '{page}/{totalPages}';
                                        // possible variables: {page}, {totalPages}, {filteredPages}, {startRow}, {endRow}, {filteredRows} and {totalRows}
                                        output: '{startRow} - {endRow} / {filteredRows} ({totalRows})'

                                    });
                        }
                );
            </script>
  <br>

  <%= link_to 'Luo uusi käyttäjä', new_user_path, class: "btn btn-primary" %>
</div>

app/views/users/new_dummy_user.html.erb
<div class="col-lg-4">

  <h1>Uusi sähköpostiton käyttäjä</h1>

  <%= render 'dummy_form' %>

</div>

app/views/users/show.html.erb
<p>Ilmoittautumiset</p>
<h2 style="margin-top: 0;"><%= @user.first_name %> <%= @user.last_name %></h2>
<% if not current_user.nil? and current_user.id == @user.id %>
    <% if @enrollments.count > 0 %>
        <% @enrollments.reverse.each do |enrollment|%>
            <h4><%= link_to enrollment.event.name, enrollment_path(enrollment.id) %> ></h4>
        <% end %>
    <% end %>

    <% if @kk_enrollment %>
        <h4>Kalevan Kierroksen yksilökilpailu <%= @year %></h4>
        <p>
            <% if @group.nil? %>
                Kierrosmaksu 50 euroa on maksettava viitenumerolla <%= @user.construct_reference_number %> Kalevan kierros ryn tilille <%= @account_number %>.
                Maksu sisältää Kalevan kierros ryn jäsenmaksun 20 euroa ja yhteiskilpailumaksun 30 euroa.
           <% end %>
        </p>
    <% else %>
        <p>Et ole vielä ilmoittautunut Kalevan kierroksen yksilökilpailuun <%= @year %>. Kalevan kierros on kuuden lajin yhteiskilpailu. Jo neljä lajia riittää hyväksyttyyn suoritukseen.</p>
        <h4><%= link_to('Ilmoittaudu yksilökilpailuun', new_kk_enrollment_path(current_user.id), :class => "btn btn-primary" ) %></h4>
    <% end %>

    <% if not @group.nil? %>
        <h4>Kalevan Kierroksen joukkuekilpailu <%= @group.name %></h4>
        <% if not @group.nil? and @group.user == current_user %>
            <p>
                Olet joukkueen kapteeni. Joukkueen kierrosmaksu 200 euroa on maksettava viitenumerolla <%= @user.construct_reference_number %>
                Kalevan kierros ry tilille <%= @account_number %>.
                Maksu sisältää joukkueen jäsenien yksilökilpailumaksut ja Kalevan kierros ryn jäsenmaksut.
            </p>
        <% else %>
            <p>Joukkueesi kierrosmaksu 200 euroa sisältää Kalevan kierroksen jäsenmaksusi ja yksilökilpailumaksun.</p>
        <% end %>
    <% end %>

    <% if not @relay_group.nil? %>
        <h4>Kalevan Kierroksen viestijoukkue <%= @relay_group.name %></h4>
        <% if not @relay_group.nil? and @relay_group.user == current_user %>
            <p>
                Olet viestijoukkueen kapteeni. Viestikilpailumaksu 60 euroa on maksettava viitenumerolla <%= @user.construct_reference_number %>
                Kalevan kierros ryn tilille <%= @account_number %>. Maksu ei sisällä Kalevan kierroksen jäsenmaksuja eikä yksilökilpailumaksuja.
            </p>
        <% end %>
    <% end %>

    <% if @group.nil? and @relay_group.nil? %>
        <h4>Et kuulu vielä joukkueeseen</h4>
        <p>Kerää viisi kaveriasi mukaan ja osallistukaa Kalevan kierrokseen joukkueena.</p>
        <h4>
            <%= link_to('Ilmoita joukkue', new_group_path(current_user.id), :class => "btn btn-primary") %>
            <!--%= link_to('Ilmoita viestijoukkue', new_relay_group_path(current_user.id), :class => "btn btn-primary") %-->
        </h4>
    <% end %>
<% end %>
<h1><a href="http://tiedot.kalevankierros.fi/" class="btn btn-primary">Omat tiedot</a></h1>
<h1><a href="http://kalevankierros.fi/" class="btn btn-default">Takaisin etusivulle</a></h1>

app/views/users/show_dummy_users.html.erb
<table id="users" class="table table-striped tablesorter-bootstrap">
  <thead>
  <tr>
    <th>Sukunimi</th>
    <th>Etunimi</th>
    <th>Käyttäjänimi</th>
    <th>Sähköposti</th>
    <th></th>
  </tr>
  </thead>
  <tfoot>
  <th>Sukunimi</th>
  <th>Etunimi</th>
  <th>Käyttäjänimi</th>
  <th>Sähköposti</th>
  <th></th>
  </tfoot>

  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.last_name %></td>
        <td><%= user.first_name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td style="min-width: 350px; text-align: center;"><%= link_to 'Näytä', user, class: "btn btn-primary btn-sm" %>
          <%= link_to 'Liitä tilastoon', join_statistic_path(user), :'data-no-turbolink' => true, class: "btn btn-primary btn-sm" %>
          <%= link_to 'Muokkaa', edit_user_path(user), class: "btn btn-warning btn-sm" %>
          <% if user.kk_enrollment == nil %>
            <%= link_to 'Ilmoita kierrokselle', enroll_dummy_user_path(user), class: 'btn btn-primary btn-sm' %>
          <% end %>
          <% if current_user != user %>
              <%= link_to 'Poista', user, method: :delete, data: {confirm: 'Are you sure?' }, id: "delete#{user.id}", class: "btn btn-danger btn-sm" %></td>
          <% end %>
          </tr>
  <% end %>
  </tbody>
</table>