config/routes.rb
Rails.application.routes.draw do
  resources :uutiset

  resources :results

  resources :event_attributes, except: [:index, :show, :new]

  resources :events
  
  resources :users
  resources :sessions, only: [:new, :create]
  resources :enrollments, only: [:create, :index]
  resources :groups, only: [:new, :create, :show]
  resources :relay_groups, only: [:new, :create, :show]
  resources :kk_enrollments, only: [:show, :update, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'enrollments/:enrollment_id/edit', to: 'enrollments#edit', as: 'edit_enrollment'
  get 'enrollments/outsider/:event_id', to:'enrollments#new_outsider_enrollment', as: 'outsider_enrollment'
  post 'enrollments/outsider/:event_id', to: 'enrollments#create_outsider_enrollment', as: 'create_outsider_enrollment'
  get 'results/year/:year/:gender/:age_group/:type', to: 'results#index_by_year', as: 'index_by_year'

  get 'uutiset/arkisto/:year', to: 'uutiset#archive_by_year', as: 'archive_by_year'

  get 'admin/kk_enrollment', to: 'static_pages#kk_enrollment'
  get 'admin/cover_image', to: 'static_pages#cover_image'
  post 'admin/change_cover_image', to: 'static_pages#change_cover_image'
  get 'admin/import_payments', to: 'static_pages#import_payments'
  put 'admin/import_payments_file', to: 'static_pages#import_payments_file', as: 'import_payments_file'
  get 'admin/list_years_awards', to: 'yearly_awards#list_years_awards', as: 'years_awards'
  get 'kk_enrollments', to: 'kk_enrollments#index'
  delete 'kk_enrollments/:id', to: 'kk_enrollments#destroy'
  post 'kk_enrollment/change', to: 'kk_enrollments#change_enrollment_status'
  get 'users/:id/kk_enrollments/new', to: 'kk_enrollments#new', as: 'new_kk_enrollment'
  post 'users/:id/kk_enrollments/new', to: 'kk_enrollments#create'

  root 'static_pages#etusivu3'
  get 'static_pages/etusivu3'

  get 'esittely/kalevankierros', to: 'static_pages#kalevankierros'
  get 'esittely/lajikuvaukset', to: 'static_pages#lajikuvaukset'
  get '/ilmoittautuminen', to: 'static_pages#ilmoittautuminen', as: 'ilmoittautuminen'
  get 'esittely/pistelasku', to: 'static_pages#pistelasku'
  get 'esittely/saannot', to: 'static_pages#saannot'
  get 'esittely/hallituksen-kokoukset', to: 'static_pages#hallituksen-kokoukset'

  get 'yhteystiedot', to: 'static_pages#yhteystiedot'
  get 'yhteystiedot/palaute', to: 'static_pages#palaute'
  get 'yhteystiedot/hallitus', to: 'static_pages#hallitus'
  get 'yhteystiedot/seurat', to: 'static_pages#seurat'
  get 'yhteystiedot/linkkeja', to: 'static_pages#linkkeja'
  get 'yhteystiedot/postituslista', to: 'static_pages#postituslista'
  get 'testi', to: 'static_pages#etusivu'
  get '2016', to: 'static_pages#etusivu2'

  get 'haastekisa', to: 'static_pages#haastekisa'

  get 'diplomas', to: 'printing_materials#export_diplomas', as: 'export_diplomas'
  get 'address_stickers', to: 'printing_materials#export_address_stickers', as: 'export_address_stickers'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'events/:event_id/event_attributes/new', to: 'event_attributes#new', as: 'add_event_attribute'
  post 'events/:event_id/event_attributes/:id', to: 'event_attributes#remove', as: 'remove_event_attribute'
  get 'events/:event_id/enrollments/new', to: 'enrollments#new', as: 'add_enrollment'
  get 'enrollments/:enrollment_id', to: 'enrollments#show', as: 'enrollment'
  delete 'enrollments/:enrollment_id', to: 'enrollments#destroy', as: 'delete_enrollment'
  get 'groups/:id/add_user', to: 'groups#add_user_to_group', as: 'add_user_to_group'
  post 'groups/:id/add_user', to: 'groups#update_user_group_relation'
  put 'groups/:id', to: 'groups#delete_user_from_group', as: 'delete_user_from_group'
  get 'relay_groups', to: 'relay_groups#index'
  get 'relay_groups/:id/add_user', to: 'relay_groups#add_user_to_relay_group', as: 'add_user_to_relay_group'
  post 'relay_groups/:id/add_user', to: 'relay_groups#update_user_relay_group_relation'
  put 'relay_groups/:id', to: 'relay_groups#delete_user_from_relay_group', as: 'delete_user_from_relay_group'
  get 'event_enrollments/:event_id/', to: 'enrollments#show_enrollments_for_event', as: 'show_enrollments'
  put 'event_enrollments/', to:'enrollments#update', as: 'add_times_and_payment_info'
  put 'kk_enrollments/', to:'kk_enrollments#update', as: 'add_payment_info'
  put 'relay_groups/', to:'relay_groups#update', as: 'add_relay_payment_info'
  get 'event_enrollments/:event_id/single', to: 'enrollments#single'
  post 'event_enrollments/:event_id/single', to: 'enrollments#update_single'
  put 'event_enrollments/:event_id/import_csv', to: 'enrollments#import_csv', as: 'import_file'
  post 'event_enrollments/:event_id/remove_all_payment_info_for_event', to: 'enrollments#remove_all_payment_info_for_event', as: 'cancel_payments'
  put 'enrollments/:enrollment_id', to: 'enrollments#delete_time', as: 'delete_time'
  put 'enrollments/:enrollment_id/payment', to: 'enrollments#update_payment_info', as: 'update_payment_info'
  post 'results/:event_id', to: 'results#calculate_points', as: 'calculate_points'
  patch 'enrollment_datas/:id', to: 'enrollment_datas#update', as: 'enrollment_datum'
  get 'results/year/:year/groups', to: 'results#with_existing_group', as: 'results_by_year_and_groups'
  get 'results/groups/female_groups', to: 'results#with_female_group', as: 'results_for_female_groups'
  get 'results/groups/mixed_groups', to: 'results#with_mixed_group', as: 'results_for_mixed_groups'
  get 'results/year/:year/relay_groups', to: 'results#with_existing_relay_group', as: 'results_by_year_and_relay_groups'
  get 'results/xlsx/participants_for_year_book', to: 'results#xlsx_results_for_year_book', as: 'individual_results_to_year_book'
  get 'results/individual/series', to: 'results#top_results_for_different_series', as: 'top_series_results'
  get 'users/:id/activate', to: 'users#new_activation', as: 'activation'
  put 'users/:id/activate', to: 'users#activate'
  get 'statistics', to: 'statistics#index', as: 'statistics'
  get 'statistics/search', to: 'statistics#index_filterable', as: 'statistics_filterable'
  get 'statistics/static', to: 'statistics#index_static'
  get 'statistics/:id', to: 'statistics#show', as: 'statistic'
  delete 'statistics/:id', to: 'statistics#destroy', as: 'delete_statistic'
  get 'statistics/:id/edit', to: 'statistics#edit', as: 'edit_statistic'
  patch 'statistics/:id', to: 'statistics#update', as: 'update_statistic'
  get 'users/:id/statistic', to: 'statistics#join', as: 'join_statistic'
  put 'users/:id/statistic', to: 'statistics#join_user_to_existing_statistic'
  post 'statistics/update/:year', to: 'statistics#update_statistics', as: 'update_statistics'
  post 'statistics/update', to: 'statistics#update_statistics'
  get '*path' => redirect('/')

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event_or_redirect, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_user_not_admin, except: [:show, :index]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    if check_for_valid_decimal(event_params[:penalty_factor])
      event_params[:penalty_factor] = (event_params[:penalty_factor].sub! ',', '.').to_f
    else
      event_params[:penalty_factor] = 1.0
    end
    if check_for_valid_decimal(event_params[:rowing_penalty])
      event_params[:rowing_penalty] = (event_params[:rowing_penalty].sub! ',', '.').to_f
    else
      event_params[:rowing_penalty] = 12.0
    end
    if event_params[:sport_type].empty?
    @event = Event.new(event_params)

      if @event.save
        redirect_to @event, flash: { success: 'Tapahtuma luotu onnistuneesti.' }
      else
        render :new
      end

    elsif event_params[:sport_type] == 'RunningEvent'
      @event = Event.new(event_params)
      @event.factor = 2000
      if @event.save
        EventAttribute.create :name => 'Tyyppi', :attribute_value => 'maraton;puolimaraton', :attribute_label => 'Valitse maraton tai puolimaraton', :attribute_type => 'radio_button', :event_id => @event.id, :attribute_index => 1
        redirect_to @event, flash: { success: 'Juoksutapahtuma luotu onnistuneesti.' }
      else
        render :new
      end
    elsif event_params[:sport_type] == 'RowingEvent'
      @event = Event.new(event_params)
      @event.factor = 3500
      if @event.save
        EventAttribute.create :name => 'Melonta', :attribute_value => 'Soutu;Melonta', :attribute_label => 'Soutu/melonta', :attribute_type => 'select', :event_id => @event.id, :attribute_index => 1
        EventAttribute.create :name => 'Tyyli', :attribute_value => 'Yksin;Vuoro', :attribute_label => 'Valitse soudatko yksin- tai vuorosoudun.', :attribute_type => 'select', :event_id => @event.id, :attribute_index => 2
        EventAttribute.create :name => 'Parin nimi', :attribute_value => '', :attribute_label => 'Jos soudat parin kanssa, kirjoita hänen nimensä tekstikenttään.', :attribute_type => 'text_field', :event_id => @event.id, :attribute_index => 3
        EventAttribute.create :name => 'Parin sukupuoli', :attribute_value => 'M;F', :attribute_label => 'Parisi sukupuoli.', :attribute_type => 'select', :event_id => @event.id, :attribute_index => 4
        EventAttribute.create :name => 'Parin syntymävuosi', :attribute_value => '', :attribute_label => 'Parisi syntymävuosi', :attribute_type => 'text_field', :event_id => @event.id, :attribute_index => 5
        EventAttribute.create :name => 'Onko pari kiertäjä', :attribute_value => 'Ei;Kyllä', :attribute_label => 'Onko parisi kiertäjä?', :attribute_type => 'select', :event_id => @event.id, :attribute_index => 6
        EventAttribute.create :name => 'kk_numero', :attribute_value => '', :attribute_label => 'Jos parisi on kiertäjä, kirjoita hänen kk-numeronsa', :attribute_type => 'text_field', :event_id => @event.id, :attribute_index => 7
        EventAttribute.create :name => 'Venekunta', :attribute_value => '', :attribute_label => 'Venekunta', :attribute_type => 'hidden', :event_id => @event.id, :attribute_index => 8
        redirect_to @event, flash: { success: 'Soututapahtuma luotu onnistuneesti.' }
      else
        render :new
      end
    elsif event_params[:sport_type] == 'SkatingEvent'
      @event = Event.new(event_params)
      @event.factor = 2800
      if @event.save
        #EventAttribute.create :name => 'Kierroslaskija', :attribute_value => 'Kyllä', :attribute_label => 'Tarvitsetko kierroslaskijan järjestäjän puolesta?', :attribute_type => 'check_box', :event_id => @event.id, :attribute_index => 1
        redirect_to @event, flash: { success: 'Luistelutapahtuma luotu onnistuneesti.' }
      else
        render :new
      end
    elsif event_params[:sport_type] == 'SkiingEvent'
      @event = Event.new(event_params)
      @event.factor = 2000
      if @event.save
        EventAttribute.create :name => 'Tyyli', :attribute_value => 'Vapaa;Perinteinen', :attribute_label => 'Valitse vapaa tai perinteinen tyyli.', :attribute_type => 'radio_button', :event_id => @event.id, :attribute_index => 1
        redirect_to @event, flash: { success: 'Hiihtotapahtuma luotu onnistuneesti' }
      else
        render :new
      end
    elsif event_params[:sport_type] == 'CyclingEvent'
      @event = Event.new(event_params)
      @event.factor = 2800
      if @event.save
        redirect_to @event, flash: { success: 'Pyöräilytapahtuma luotu onnistuneesti' }
      else
        render :new
      end
    elsif event_params[:sport_type] == 'OrienteeringEvent'
      @event = Event.new(event_params)
      @event.factor = 1300
      if @event.save
        EventAttribute.create :name => 'Emit', :attribute_value => 'Kyllä', :attribute_label => 'Tarvitsetko emit-lähettimen järjestäjän puolesta?', :attribute_type => 'check_box', :event_id => @event.id, :attribute_index => 1
        redirect_to @event, flash: { success: 'Suunnistustapahtuma luotu onnistuneesti' }
      else
        render :new
      end
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, flash: { success: 'Tapahtumaa muokattu onnistuneesti.' }
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, flash: { success: 'Tapahtuma poistettiin onnistuneesti.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def check_for_valid_decimal(decimal_param)
    /\d{1,2},\d{1,2}/ === decimal_param
  end

    def set_event_or_redirect
      @event = Event.find_by id: params[:id]
      return if @event

      redirect_to :root
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start_date, :end_date, :second_end_date, :price, :second_price, :description, :open, :penalty_factor, :sport_type, :rowing_penalty, :account_number, :payment_receiver)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= bootstrap_form_for(@event, html: {autocomplete: "off"}) do |f| %>
    <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
            <% @event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <% if @event.new_record? %>
      <%= f.select :sport_type, options_for_select([['Tyhjä', ''],['Juoksu', 'RunningEvent'], ['Soutu', 'RowingEvent'], ['Hiihto', 'SkiingEvent'], ['Suunnistus', 'OrienteeringEvent'], ['Luistelu', 'SkatingEvent'], ['Pyöräily', 'CyclingEvent']]), :class => "form-control", label: 'Jos haluat valmiin pohjan tapahtumalle, valitse jokin seuraavista:' %>
      <% end %>
      <%= f.text_field :name, label: 'Tapahtuman nimi (käytä samaa kuin websivuilla)' %>
      <%= f.date_select :start_date, label: 'Tapahtuman ilmoittautumisen aloituspäivämäärä' %>
      <%= f.date_select :end_date, label: 'Tapahtuman ilmoittautumisen päättymispäivämäärä (noin viikko ennen tapahtumaa)' %>
      <%= f.date_select :second_end_date, label: 'Tapahtuman jälki-ilmoittautumisen päättymispäivämäärä (noin 2vko tapahtuman jälkeen)' %>
      <%= f.text_field :price, label: 'Osallistumismaksu sentteinä' %>
      <%= f.text_field :second_price, label: 'Jälki-ilmoittautumismaksu sentteinä' %>
      <%= f.text_area :description, label: 'Tapahtuman kuvaus (eri riveille paikka, aika, matka, järjestäjä, ...)' %>
      <%= f.text_field :penalty_factor, label: 'Loppuajan pistelaskun rangaistuskerroin, jos sellainen on. Soudussa tätä käytetään mahdollisessa naisten sekasarjan rangaistuslisäyksenä aikaan minuutteina.' %>
      <%= f.text_field :rowing_penalty, label: 'Vuorosoudun rangaistuslisä. Käytetään vain soudussa. Jos valitset tapahtuman pohjaksi soudun muista lisätä tämä! Oletuksena arvo on 12 minuuttia.' %>
      <%= f.text_field :account_number, label: 'Tapahtumakohtainen tilinumero. Lähetetään ilmoittautujalle sähköpostilla. Syötä IBAN-muodossa. Jos maksua ei ole, voit jättää tämän kentän tyhjäksi.' %>
      <%= f.text_field :payment_receiver, label: 'Tapahtuman maksun saaja.' %>
    </div>

    <div class="actions">
      <% if defined?(subpage) && subpage.to_s == 'edit' %>
          <%= f.submit "Tallenna muutokset", :class => "btn btn-primary" %>
      <% else %>
          <%= f.submit "Luo tapahtuma", :class => "btn btn-primary" %>
      <% end %>
    </div>

            <style type="text/css">.input-group .form-control {
                margin: 0px !important;
            }</style>
    <script type="text/javascript">
        $(document).ready(function() {
            $('form').bootstrapValidator({
                message: 'Virheellinen syöte',
                feedbackIcons: {
                    valid: 'glyphicon glyphicon-ok',
                    invalid: 'glyphicon glyphicon-asterisk',
                    validating: 'glyphicon glyphicon-refresh'
                },
                fields: {
                    'event[name]': {
                        validators: {
                            notEmpty: {
                                message: 'Tapahtuman nimi ei voi olla tyhjä'
                            }
                        }
                    },
                    'event[description]': {
                        validators: {
                            notEmpty: {
                                message: 'Syötä tapahtumalle kuvaus'
                            }
                        }
                    }
                }
            });
        });
    </script>
<% end %>

app/views/events/edit.html.erb
  <h2>Muokkaa tapahtumaa</h2>

  <%= render 'form', :subpage => 'edit'  %>

  <%= link_to 'Tapahtuman tiedot', @event %> |

  <%= link_to 'Näytä kaikki tapahtumat', events_path %>

app/views/events/index.html.erb
<div class="col-lg-12">
  <h1>Selaa tapahtumia</h1>
  <p>Tällä sivulla voit tarkastella tapahtumien ilmoittautumispäivämääriä, sekä ilmoittautua niihin. Muista ilmoittautua ajoissa osakilpailuun. Osakilpailuihin ilmoittautuminen tarvitaan, jotta pisteiden laskeminen ja tulosten kirjaaminen onnistuisi.</p>

<table id="events" class="table table-striped tablesorter-bootstrap">
  <thead>
    <tr>
      <th>Nimi:</th>
      <th>Alkaa:</th>
      <th>Päättyy:</th>
      <th>Ilmoittaudu</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.start_date.strftime("%-d.%-m.%-Y") %></td>
        <td><%= event.end_date.strftime("%-d.%-m.%-Y") %></td>
        <td>
          <% if Date.today >= event.start_date && Date.today <= event.second_end_date %>
          <%= link_to 'Ilmoittaudu tapahtumaan', add_enrollment_path({:event_id => event.id}) %>
          <% else %>
          Tapahtumaan ei voi ilmoittautua
          <% end %>
        </td>
        <td><%= link_to 'Näytä tiedot', event, class: "btn btn-primary btn-sm"%></td>
        <td><% if user_is_admin? %><%= link_to 'Muokkaa', edit_event_path(event), class: "btn btn-warning btn-sm"  %> <% end %></td>
        <td><% if user_is_admin? %><%= link_to 'Poista', event, method: :delete, data: { confirm: 'Oletko varma että haluat poistaa tapahtuman?' }, class: "btn btn-danger btn-sm" %><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>* Ulkopuolisena tapahtumaan ilmoittautuminen tarkoittaa sitä, että et ilmoittaudu tapahtumaan kiertäjänä. Sinun ei tällöin tarvitse ilmoittautua Kalevan Kierrokselle. Jos haluat ilmoittautua tapahtumaan kiertäjänä, rekisteröidy ja kirjaudu sisään, sekä ilmoittaudu kierrokselle.
Huomaa, että kaikki tapahtumat eivät ole avoimia. Näihin ei voi osallistua ilmoittautumatta kierrokselle.</p>
  <script type="text/javascript">

      $(document).ready(function () {
                  $.extend($.tablesorter.themes.bootstrap, {
                      // these classes are added to the table. To see other table classes available,
                      // look here: http://twitter.github.com/bootstrap/base-css.html#tables
                      table      : 'table table-bordered',
                      caption    : 'caption',
                      header     : 'bootstrap-header', // give the header a gradient background
                      footerRow  : '',
                      footerCells: '',
                      icons      : '', // add "icon-white" to make them white; this icon class is added to the <i> in the header
                      sortNone   : 'bootstrap-icon-unsorted',
                      sortAsc    : 'icon-chevron-up glyphicon glyphicon-chevron-up',     // includes classes for Bootstrap v2 & v3
                      sortDesc   : 'icon-chevron-down glyphicon glyphicon-chevron-down', // includes classes for Bootstrap v2 & v3
                      active     : '', // applied when column is sorted
                      hover      : '', // use custom css here - bootstrap class may not override it
                      filterRow  : '', // filter row class
                      even       : '', // odd row zebra striping
                      odd        : ''  // even row zebra striping
                  });

                  $("#events").tablesorter({
                      headers: {3: {sorter: false}, 4: {sorter: false}, 5: {sorter: false}},
                      theme: "bootstrap",
                      headerTemplate: '{content} {icon}',
                      widgets: [ "uitheme" ]
                  });
              }
      );
  </script>

<% if user_is_admin? %>
     <%= link_to 'Luo uusi tapahtuma', new_event_path, class: "btn btn-primary" %>

<% end %>
</div>

app/views/events/new.html.erb
  <h2>Luo uusi tapahtuma</h2>

  <%= render 'form' %>

app/views/events/show.html.erb
    <h2 class="eventtitle">
      <%= @event.name %>
    </h2>

    <p>
      <strong>Ilmoittautuminen alkaa:</strong>
      <%= @event.start_date %>
    </p>

    <p>
      <strong>Ilmoittautuminen päättyy:</strong>
      <%= @event.end_date %>
    </p>

    <p>
      <strong>Kuvaus:</strong><br/>
      <%= @event.description %>
    </p>

    <% if Date.today <= @event.second_end_date && Date.today >= @event.start_date %>
        <p>
            <%= link_to 'Näytä ilmoittautumislomake', add_enrollment_path({:event_id => @event.id}), :class => "btn btn-primary" %>
        </p>
    <% else %>
        <strong>Tapahtuman ilmoittautuminen ei ole auki.</strong>
    <% end %>

    <h1><a href="http://kalevankierros.fi/" class="nappula btn btn-default">Takaisin etusivulle</a></h1>

    <% if user_is_admin? %>
        <h2>Seuraavat kentät vain ylläpitäjille:</h2>
        <% event_price = @event.current_price %>
        <% if event_price and event_price > 0 %>
            <p>
                <span id="event_price" class="hidden"><%= event_price %></span>
                Tapahtuman osallistumismaksu on <%= "%.2f" % (event_price/100.0) %> euroa.
            </p>
        <% end %>

        <strong>Tapahtuman kentät:</strong><br>
        <% #form_for(@enrollment) do |e| %>
        <% @event.event_attributes.where(removed: false).each do |f| %>
                <div style="background-color: rgba(255, 0, 0, 0.2); margin: 0 0 10px 0;">
                <% if f.attribute_type != "hidden" %>
                    <strong><%= f.attribute_label %></strong>
                <% end %>
                <div class="field">
                <% if f.attribute_type == "select" %>
                    <%= select_tag :sel, options_for_select(f.get_options_to_form), {:class => 'payfield', "data-prices" => f.get_prices.to_s} %><br>
                    Hinnat: <%= f.payment_value %><br>
                    Jälki-ilmoittautumisen hinnat: <%= f.second_payment_value %>
                <% end %>

                <% if f.attribute_type == "radio_button" %>
                    <% i = 0 %>
                    <% checked = true %>
                    <% f.get_options_to_form.each do |v, p| %>
                    <%= radio_button_tag(:sel, p, checked, {:class => 'payfield', "data-prices" => f.get_prices.to_s, "data-index" => i}) %>
                    <%= label_tag(:radio, v) %><br>
                    <% checked = false %>
                    <% i = i + 1 %>
                <% end %>
                Hinnat: <%= f.payment_value %><br>
                Jälki-ilmoittautumisen hinnat: <%= f.second_payment_value %>
                <% end %>

                <% if f.attribute_type == "check_box" %>
                <% f.get_options_to_form.each do |v, p| %>
                    <%= check_box_tag(:sel, p, false, {:class => 'payfield', "data-prices" => f.get_prices.to_s}) %>
                    <%= label_tag(:check, v) %><br>
                <% end %>
                Hinnat: <%= f.payment_value %><br>
                Jälki-ilmoittautumisen hinnat: <%= f.second_payment_value %>
                <% end %>
                <% if f.attribute_type == "text_field" %>
                  <%= text_field_tag(:sel, f.attribute_value) %>
                <% end %>
                <% if f.attribute_type == "plain_text" %>
                  <%= f.attribute_value %>
                <% end %>
                </div>
		<%= link_to 'Poista kenttä', remove_event_attribute_path({:event_id => @event.id, :id => f.id}), :method => :post, :class => "btn btn-primary", :data => {:confirm => 'Haluatko varmati poistaa kentän?'} %>
                </div>
            <% end %>
        <% #end %>
        <p><span id="price_sum"></span></p>
        <%= link_to 'Lisää kenttä', add_event_attribute_path({:event_id => @event.id}) %> |
        <%= link_to 'Muokkaa tapahtumaa', edit_event_path(@event) %> |
        <%= link_to 'Palaa tapahtumiin', events_path %>
    <% end %>

<script type="text/javascript">
        $(document).ready(function() {
            updateSum();
            $(".payfield").each(function() {
                $(this).change(function() {
                    updateSum();
                });
            });
        
            function updateSum() {
                var sum = 0;
                if ($("#event_price").length) {
                    sum = sum + parseInt($("#event_price").html())
                }
                $(".payfield").each(function() {
                    if($(this).is(":checkbox")) {
                        if($(this).is(":checked")) {
                            sum = sum + $(this).data("prices")[0];
                        }
                    } else if($(this).is("select")) {
                        var prices = $(this).data("prices");
                        sum = sum + prices[$(this)[0].selectedIndex];
                    } else if($(this).is(":radio")) {
                        var prices = $(this).data("prices");
                        if($(this).is(":checked")) {
                            sum = sum + $(this).data("prices")[ $(this).data('index')];
                        }
                    }
                });
                sum = sum/100
                if(sum > 0) {
                    $("#price_sum").html("Ilmoittautumismaksu on yhteensä " + sum.toFixed(2) + " euroa.");
                } else {
                    $("#price_sum").html("");
                }
            };     
        });
    </script>