config/routes.rb
Rails.application.routes.draw do
  resources :uutiset

  resources :results

  resources :event_attributes, except: [:index, :show, :new]

  resources :events
  
  resources :users
  resources :sessions, only: [:new, :create]
  resources :enrollments, only: [:create, :index]
  resources :groups, only: [:new, :create, :show]
  resources :relay_groups, only: [:new, :create, :show]
  resources :kk_enrollments, only: [:show, :update, :edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'enrollments/:enrollment_id/edit', to: 'enrollments#edit', as: 'edit_enrollment'
  get 'enrollments/outsider/:event_id', to:'enrollments#new_outsider_enrollment', as: 'outsider_enrollment'
  post 'enrollments/outsider/:event_id', to: 'enrollments#create_outsider_enrollment', as: 'create_outsider_enrollment'
  get 'results/year/:year/:gender/:age_group/:type', to: 'results#index_by_year', as: 'index_by_year'

  get 'uutiset/arkisto/:year', to: 'uutiset#archive_by_year', as: 'archive_by_year'

  get 'admin/kk_enrollment', to: 'static_pages#kk_enrollment'
  get 'admin/cover_image', to: 'static_pages#cover_image'
  post 'admin/change_cover_image', to: 'static_pages#change_cover_image'
  get 'admin/import_payments', to: 'static_pages#import_payments'
  put 'admin/import_payments_file', to: 'static_pages#import_payments_file', as: 'import_payments_file'
  get 'admin/list_years_awards', to: 'yearly_awards#list_years_awards', as: 'years_awards'
  get 'kk_enrollments', to: 'kk_enrollments#index'
  delete 'kk_enrollments/:id', to: 'kk_enrollments#destroy'
  post 'kk_enrollment/change', to: 'kk_enrollments#change_enrollment_status'
  get 'users/:id/kk_enrollments/new', to: 'kk_enrollments#new', as: 'new_kk_enrollment'
  post 'users/:id/kk_enrollments/new', to: 'kk_enrollments#create'

  root 'static_pages#etusivu3'
  get 'static_pages/etusivu3'

  get 'esittely/kalevankierros', to: 'static_pages#kalevankierros'
  get 'esittely/lajikuvaukset', to: 'static_pages#lajikuvaukset'
  get '/ilmoittautuminen', to: 'static_pages#ilmoittautuminen', as: 'ilmoittautuminen'
  get 'esittely/pistelasku', to: 'static_pages#pistelasku'
  get 'esittely/saannot', to: 'static_pages#saannot'
  get 'esittely/hallituksen-kokoukset', to: 'static_pages#hallituksen-kokoukset'

  get 'yhteystiedot', to: 'static_pages#yhteystiedot'
  get 'yhteystiedot/palaute', to: 'static_pages#palaute'
  get 'yhteystiedot/hallitus', to: 'static_pages#hallitus'
  get 'yhteystiedot/seurat', to: 'static_pages#seurat'
  get 'yhteystiedot/linkkeja', to: 'static_pages#linkkeja'
  get 'yhteystiedot/postituslista', to: 'static_pages#postituslista'
  get 'testi', to: 'static_pages#etusivu'
  get '2016', to: 'static_pages#etusivu2'

  get 'haastekisa', to: 'static_pages#haastekisa'

  get 'diplomas', to: 'printing_materials#export_diplomas', as: 'export_diplomas'
  get 'address_stickers', to: 'printing_materials#export_address_stickers', as: 'export_address_stickers'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'events/:event_id/event_attributes/new', to: 'event_attributes#new', as: 'add_event_attribute'
  post 'events/:event_id/event_attributes/:id', to: 'event_attributes#remove', as: 'remove_event_attribute'
  get 'events/:event_id/enrollments/new', to: 'enrollments#new', as: 'add_enrollment'
  get 'enrollments/:enrollment_id', to: 'enrollments#show', as: 'enrollment'
  delete 'enrollments/:enrollment_id', to: 'enrollments#destroy', as: 'delete_enrollment'
  get 'groups/:id/add_user', to: 'groups#add_user_to_group', as: 'add_user_to_group'
  post 'groups/:id/add_user', to: 'groups#update_user_group_relation'
  put 'groups/:id', to: 'groups#delete_user_from_group', as: 'delete_user_from_group'
  get 'relay_groups', to: 'relay_groups#index'
  get 'relay_groups/:id/add_user', to: 'relay_groups#add_user_to_relay_group', as: 'add_user_to_relay_group'
  post 'relay_groups/:id/add_user', to: 'relay_groups#update_user_relay_group_relation'
  put 'relay_groups/:id', to: 'relay_groups#delete_user_from_relay_group', as: 'delete_user_from_relay_group'
  get 'event_enrollments/:event_id/', to: 'enrollments#show_enrollments_for_event', as: 'show_enrollments'
  put 'event_enrollments/', to:'enrollments#update', as: 'add_times_and_payment_info'
  put 'kk_enrollments/', to:'kk_enrollments#update', as: 'add_payment_info'
  put 'relay_groups/', to:'relay_groups#update', as: 'add_relay_payment_info'
  get 'event_enrollments/:event_id/single', to: 'enrollments#single'
  post 'event_enrollments/:event_id/single', to: 'enrollments#update_single'
  put 'event_enrollments/:event_id/import_csv', to: 'enrollments#import_csv', as: 'import_file'
  post 'event_enrollments/:event_id/remove_all_payment_info_for_event', to: 'enrollments#remove_all_payment_info_for_event', as: 'cancel_payments'
  put 'enrollments/:enrollment_id', to: 'enrollments#delete_time', as: 'delete_time'
  put 'enrollments/:enrollment_id/payment', to: 'enrollments#update_payment_info', as: 'update_payment_info'
  post 'results/:event_id', to: 'results#calculate_points', as: 'calculate_points'
  patch 'enrollment_datas/:id', to: 'enrollment_datas#update', as: 'enrollment_datum'
  get 'results/year/:year/groups', to: 'results#with_existing_group', as: 'results_by_year_and_groups'
  get 'results/groups/female_groups', to: 'results#with_female_group', as: 'results_for_female_groups'
  get 'results/groups/mixed_groups', to: 'results#with_mixed_group', as: 'results_for_mixed_groups'
  get 'results/year/:year/relay_groups', to: 'results#with_existing_relay_group', as: 'results_by_year_and_relay_groups'
  get 'results/xlsx/participants_for_year_book', to: 'results#xlsx_results_for_year_book', as: 'individual_results_to_year_book'
  get 'results/individual/series', to: 'results#top_results_for_different_series', as: 'top_series_results'
  get 'users/:id/activate', to: 'users#new_activation', as: 'activation'
  put 'users/:id/activate', to: 'users#activate'
  get 'statistics', to: 'statistics#index', as: 'statistics'
  get 'statistics/search', to: 'statistics#index_filterable', as: 'statistics_filterable'
  get 'statistics/static', to: 'statistics#index_static'
  get 'statistics/:id', to: 'statistics#show', as: 'statistic'
  delete 'statistics/:id', to: 'statistics#destroy', as: 'delete_statistic'
  get 'statistics/:id/edit', to: 'statistics#edit', as: 'edit_statistic'
  patch 'statistics/:id', to: 'statistics#update', as: 'update_statistic'
  get 'users/:id/statistic', to: 'statistics#join', as: 'join_statistic'
  put 'users/:id/statistic', to: 'statistics#join_user_to_existing_statistic'
  post 'statistics/update/:year', to: 'statistics#update_statistics', as: 'update_statistics'
  post 'statistics/update', to: 'statistics#update_statistics'
  get '*path' => redirect('/')

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController

  before_action :authenticate, only: [:new, :create, :show, :show_enrollments_for_event, :index, :destroy, :update, :edit, :update_single,
                                     :update_payment_info, :remove_all_payment_info_for_event]
  before_action :check_for_existing_enrollment, only:  [:new, :create]
  before_action :set_enrollment_or_redirect, only: [:show, :destroy, :edit]
  before_action :redirect_if_user_not_admin, only: [:show_enrollments_for_event, :index, :destroy, :update, :edit, :update_single,
                                                    :update_payment_info, :remove_all_payment_info_for_event]

  def new
    @event = Event.find_by id: params[:event_id]
    if @event
      @user = current_user
      if Date.today < @event.start_date
        redirect_to root_path, flash: { notice: 'Tapahtumaan ei voi vielä ilmoittautua' }
        return
      end
      if Date.today > @event.second_end_date
        redirect_to root_path, flash: { notice: 'Tapahtumaan ei voi enää ilmoittautua' }
        return
      end

      @enrollment = Enrollment.new
      @enrollment.enrollment_datas.build
    else
      redirect_to root_path
    end
  end

  def new_outsider_enrollment
    @event = Event.find_by id: params[:event_id]
    if not @event or not @event.open
      redirect_to :root and return
    end
    if Date.today > @event.second_end_date
      redirect_to root_path, flash: { notice: 'Tapahtumaan ei voi enää ilmoittautua' } and return
    end
    @user = User.new
    @attributes = @event.event_attributes
  end

  def index
    @events = Event.all
  end

  def edit
    @datas = @enrollment.enrollment_datas
  end

  def create
    event = Event.find_by id: params[:enrollment][:event_id]
    user  = current_user
    if event && user
      create_enrollment(event, user, enrollment_params, params, true)
    else
      redirect_to root_path
    end
  end

  def create_enrollment(event, user, enrollment_values, values, user_generated)
    data_list = []
    attrs = event.event_attributes.select {|a| a.attribute_type != 'plain_text' and a.attribute_type != 'hidden' and a.removed == false }
    # loop for creating information for data
    attrs.each do |a|
      if user_generated
        attribute_key = a.name
      else
        attribute_key = a.name.downcase.to_sym
      end

      if !values.has_key? attribute_key
        if user_generated
          redirect_to root_path, flash: { error: 'Ilmoittautuminen epäonnistui. Täytä lomake uudelleen ja varmista, että pakolliset kentät on täytetty.' }
        end
        return
      end
      if values[attribute_key].kind_of?(Array)
        value = values[attribute_key].join(' ')
        attribute_index = EventAttribute.where(event_id: event.id).where(name: a.name).first.attribute_index
        data_list.append(EnrollmentData.new(name: a.name, value: value, attribute_index: attribute_index))
      else
        attribute_index = EventAttribute.where(event_id: event.id).where(name: a.name).first.attribute_index
        data_list.append(EnrollmentData.new(name: a.name, value: values[attribute_key], attribute_index: attribute_index))
      end
    end

    @enrollment = Enrollment.new(enrollment_values)
    @enrollment.user = user

    if !user_generated && values[:aika]
      @enrollment.time = to_seconds(values[:aika])
    end

    if !user_generated && values[:maksettu] && (is_float? values[:maksettu])
      @enrollment.paid = (values[:maksettu].to_f * 100.0).to_i
    end

    if !user_generated && values[:arvopiv] && (is_date? values[:arvopiv])
      @enrollment.value_date = Date::strptime(values[:arvopiv], "%d.%m.%Y")
    end

    if @enrollment.save
      data_list.each do |d|
        d.enrollment_id = @enrollment.id
        d.save
      end

      if user
        if event.sport_type == 'RowingEvent'
          style = @enrollment.enrollment_datas.find_by name:'Tyyli'
          pair_name_datum = @enrollment.enrollment_datas.find_by name:'Parin nimi'
          pair_name = pair_name_datum.value&.split(' ')
          if(style.value == 'Vuoro')
            if user_generated && pair_name.length != 2
              @enrollment.destroy
              if user_generated
                redirect_back(fallback_location: root_path, flash: { error: 'Parin nimi ei ole kirjoitettu oikein. Kirjoita parisi nimeksi etunimi ja sukunimi välilyönnillä erotettuna.' })
              end
              return
            end
            other_rower = @enrollment.enrollment_datas.find_by name:'kk_numero'
            if other_rower.value != ''
              if not enroll_other_rower_to_event(other_rower.value, user, @enrollment, event)
                @enrollment.destroy
                if user_generated
                  redirect_back(fallback_location: root_path, flash: { error: 'Toista henkilöä ei löytynyt kannasta. Jos hän ei ole kiertäjä, jätä kk-numeron kenttä tyhjäksi.' })
                end
                return
              end
            else
              gender = @enrollment.enrollment_datas.find_by(name: 'Parin sukupuoli').value
              birth_year = @enrollment.enrollment_datas.find_by(name: 'Parin syntymävuosi').value
              if not create_new_user_for_outsider_rower(pair_name[0], pair_name[1], gender, birth_year, user, @enrollment, event)
                @enrollment.destroy
                if user_generated
                  redirect_back(fallback_location: root_path, flash: { error: 'Jokin meni pieleen. Tarkista tiedot ja yritä uudestaan.' })
                end
                return
              end
            end
          end
        end
        user.enrollments << @enrollment
        if user_generated
          EnrollmentMailer.send_enrollment_email(user, event, @enrollment).deliver
        end
      end

      if user_generated
        flash[:success] = "Ilmoittautumisesi tapahtumaan on kirjattu."
        redirect_to enrollment_path(@enrollment.id)
      end
    else
      if user_generated
        render :new
      end
      return
    end
  end

  def create_outsider_enrollment
    if User.last
        latest = User.last.id + 1
    else
        latest = 1
    end
    name = "outsider#{latest}"
    params[:user][:username] = name
    params[:user][:password] = 'X92fueslwR'
    params[:user][:password_confirmation] = 'X92fueslwR'
    user_params = params.require(:user).permit(:first_name, :last_name, :username, :email, :phone_number, :city, :street_address, :postal_code, :birth_date, :gender, :password, :password_confirmation)

    user = User.new(user_params)

    if user.save
      outsider_number = 1100000+user.id
      user.update_attribute :kk_number, outsider_number
      event = Event.find_by id: params[:event_id]
      if event && event.open
        data_list = []
        attrs = event.event_attributes.select {|a| a.attribute_type != 'plain_text' and a.attribute_type != 'hidden' and a.removed == false }
        attrs.each do |a|
          if !params[:enrollment].has_key? a.name
            redirect_to root_path and return
          end
          if params[:enrollment][a.name].kind_of?(Array)
            value = params[:enrollment][a.name].join(' ')
            attribute_index = EventAttribute.where(event_id: event.id).where(name: a.name).first.attribute_index
            data_list.append(EnrollmentData.new(name:a.name, value:value, attribute_index: attribute_index))
          else
            attribute_index = EventAttribute.where(event_id: event.id).where(name: a.name).first.attribute_index
            data_list.append(EnrollmentData.new(name:a.name, value:params[:enrollment][a.name], attribute_index: attribute_index))
          end
        end

        @enrollment = Enrollment.new(event_id: event.id)
        if @enrollment.save
          data_list.each do |d|
            d.enrollment_id = @enrollment.id
            d.save
          end
          if event.sport_type == 'RowingEvent'
            pair = @enrollment.enrollment_datas.find_by(name: 'Tyyli').value
            if pair == 'Vuoro'
              other_rower_is_user = @enrollment.enrollment_datas.find_by(name: 'Onko pari kiertäjä').value
              if other_rower_is_user == 'Kyllä'
                @enrollment.destroy
                user.destroy
                redirect_back(fallback_location: root_path, flash: { error: 'Ulkopuolisena et voi ilmoittaa kiertäjää pariksesi.' }) and return
              else
                other_name = @enrollment.enrollment_datas.find_by(name:'Parin nimi').value
                name_split = other_name.split(' ')
                if name_split.length != 2
                  @enrollment.destroy
                  user.destroy
                  redirect_back(fallback_location: root_path, flash: { error: 'Parin nimi ei ole kirjoitettu oikein. Kirjoita etunimi ja sukunimi välilyönnillä erotettuna' }) and return
                end
                birth_year = @enrollment.enrollment_datas.find_by(name:'Parin syntymävuosi').value
                gender = @enrollment.enrollment_datas.find_by(name:'Parin sukupuoli').value
                if not create_new_user_for_outsider_rower(name_split[0], name_split[1], gender, birth_year, user, @enrollment, event)
                  @enrollment.destroy
                  user.destroy
                  redirect_back(fallback_location: root_path, flash: { error: 'Jotain meni pieleen. Tarkista tietojen oikeellisuus ja yritä uudestaan.' }) and return
                end
              end
            end
          end
          user.enrollments << @enrollment
          EnrollmentMailer.send_enrollment_email(user, event, @enrollment)
        else
          redirect_back(fallback_location: root_path, flash: { error: 'Jotain meni pieleen' }) and return
        end
      end
    else
      redirect_back(fallback_location: root_path, flash: { error: 'Et antanut kaikkia tietoja' }) and return
    end

app/views/enrollments/edit.html.erb
<h1>Muokkaa ilmoittautumisen tietoja</h1>
<% @enrollment.enrollment_datas.each do |d| %>
    <%= form_for(d, method: :patch) do |f| %>
        <%= f.label :name %><br>
        <%= f.text_field :value %>
        <%= f.submit %>
    <% end %>
<% end %>

app/views/enrollments/index.html.erb
<div class="col-md-8">

  <h1>Ilmoittautumiset tapahtumittain</h1>
<p>Valitse tapahtuma alta: </p>
  <table id="eventenrollments" class="table table-striped tablesorter-blue">
    <thead>
    <tr>
      <th>Nimi:</th>
      <th>Alkamispäivä:</th>
    </tr>
    </thead>
    <tbody>
  <% @events.each do |event| %>
        <tr>
          <td><%= link_to event.name, show_enrollments_path(event.id) %></td>
          <td><%=event.start_date.strftime("%-d.%-m.%-Y") %></td>
    </tr>
  <% end %>

    </tbody>
  </table>
  <script type="text/javascript">
      $(document).ready(function () {
                  $.extend($.tablesorter.themes.bootstrap, {
                      // these classes are added to the table. To see other table classes available,
                      // look here: http://twitter.github.com/bootstrap/base-css.html#tables
                      table      : 'table table-bordered',
                      caption    : 'caption',
                      header     : 'bootstrap-header', // give the header a gradient background
                      footerRow  : '',
                      footerCells: '',
                      icons      : '', // add "icon-white" to make them white; this icon class is added to the <i> in the header
                      sortNone   : 'bootstrap-icon-unsorted',
                      sortAsc    : 'icon-chevron-up glyphicon glyphicon-chevron-up',     // includes classes for Bootstrap v2 & v3
                      sortDesc   : 'icon-chevron-down glyphicon glyphicon-chevron-down', // includes classes for Bootstrap v2 & v3
                      active     : '', // applied when column is sorted
                      hover      : '', // use custom css here - bootstrap class may not override it
                      filterRow  : '', // filter row class
                      even       : '', // odd row zebra striping
                      odd        : ''  // even row zebra striping
                  });

                  $("#eventenrollments").tablesorter({
                      theme: "bootstrap",
                      headerTemplate: '{content} {icon}',
                      widgets: [ "uitheme" ]
                  });
              }
      );
  </script>
</div>

app/views/enrollments/new.html.erb
<%= render 'form' %>

<h1><a href="http://kalevankierros.fi/" class="nappula btn btn-default">Takaisin etusivulle</a></h1>

app/views/enrollments/show.html.erb
    <h2><%= @enrollment.event.name %></h2>
    <h3><%= @enrollment.user.first_name %> <%= @enrollment.user.last_name %></h3>
    <% @data.each do |data| %>
        <% if data.value %>
            <p><%= data.value %></p>
        <% end %>
    <% end %>
    <% if !@account_number.empty? and @price > 0 %>
        <h4>Maksutiedot</h4>
        <p>Tilinumero: <%= @account_number %></p>
        <p>Saaja: <%= @receiver %></p>
        <p>Viitenumero: <%= @reference_number %></p>
        <p>Osallistumismaksu: <%= @price %> euroa</p>
        <p>Eräpäivä: <%= @pay_day %></p>
    <% end %>
    <h1><%= link_to 'Omiin tietoihin', user_path(current_user), :class => "btn btn-primary" %></h1>
    <% if user_is_admin? %>
      <%= link_to 'Peru ilmoittautuminen', @enrollment, method: :delete, data: { confirm: 'Oletko varma että haluat perua ilmoittautumisen?' } %>
    <% end %>
    <h1><a href="http://kalevankierros.fi/" class="btn btn-default">Takaisin etusivulle</a></h1>

app/views/enrollments/show_enrollments_for_event.html.erb
<div class="col-lg-12">

  <h1><%= @event.name %></h1>
  <%= form_tag('/event_enrollments', method: :put) do %>

  <table id="eventparticipants" class="table table-striped tablesorter-bootstrap">
    <thead>
    <th>Etunimi</th>
    <th>Sukunimi</th>
    <th>Osallistujan sähköposti</th>
    <th>KK-numero</th>
    <% @event.event_attributes.where(removed: false).where.not(attribute_index: nil).order('attribute_index asc').each do |attr| %>
        <th><%= attr.name %></th>
    <% end %>
    <th>Viitenumero</th>
    <th>Maksettava</th>
    <th>Maksettu</th>
    <th>Arvopäivä&nbsp;&nbsp;&nbsp;</th>
    <th>Lisää aika</th>
    <th>Poista aika</th>
    <th>Peru</th>
    <th>Muokkaa</th>
    </thead>
    <tbody>
    <% @event.enrollments.each do |enrollment| %>
        <tr>
          <td><%= enrollment.user.first_name %></td>
          <td><%= enrollment.user.last_name %></td>
          <td><%= enrollment.user.email %></td>
          <td><%= enrollment.user.kk_number %></td>
          <% enrollment.user.get_formatted_enrollment_data_for_event(@event.id).each do |data| %>
            <td><%= data %></td>
          <% end %>
          <td><%= enrollment.construct_reference_number %></td>
          <td><%= enrollment.calculate_price %></td>
          <td ><div class="form-group">
          <% if enrollment.paid.nil? %>
            <%= text_field_tag "paid[#{enrollment.id}]", nil, maxlength: 8, :class => "form-control min-width" %>
          <% else %>
            <%= text_field_tag "paid[#{enrollment.id}]", enrollment.paid/100.0, :class => "form-control min-width"  %>
          <% end %>
          </div></td>
          <td><div class="form-group">
          <% if enrollment.value_date.nil? %>
            <%= text_field_tag "value_date[#{enrollment.id}]", nil, :class => "form-control min-width" %>
          <% else %>
            <%= text_field_tag "value_date[#{enrollment.id}]", enrollment.value_date.strftime("%d.%m.%Y"), :class => "form-control"  %>
          <% end %>
          </div>
          </td>
          <td ><div class="form-group">
          <% if enrollment.time.nil? %>
            <%= text_field_tag "times[#{enrollment.id}]", nil, maxlength: 8, :class => "form-control min-width" %>
          <% else %>
            <%= text_field_tag "times[#{enrollment.id}]", seconds_to_human_form(enrollment.time), :class => "form-control min-width"  %>
          <% end %>
          </div></td>
          <td><%= link_to 'Poista aika', delete_time_path(enrollment.id), method: :put, class: "btn btn-warning btn-sm" %></td>
          <td><%= link_to 'Poista', enrollment_path(enrollment.id), class: "btn btn-danger btn-sm" %></td>
          <td><%= link_to 'Muokkaa', edit_enrollment_path(enrollment.id), class: "btn" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <%= submit_tag 'Päivitä ajat ja maksutiedot', :class => "btn btn-primary" %><br>
  <% end %>
  <style type="text/css">.min-width{min-width: 100px;}</style><br>
  <p>
    <%= link_to 'Poista kaikki maksutiedot', cancel_payments_path(@event.id), method:'post', :class =>'btn btn-primary' %><br>
  </p>
  <p>
    <%= link_to 'Lataa csv-tiedostona', show_enrollments_path(@event.id, format: :csv) %><br>
    <%= link_to 'Lataa excel-tiedostona (xls)', show_enrollments_path(@event.id, format: :xls) %><br>
    <%= link_to 'Lataa excel-tiedostona (xlsx)', show_enrollments_path(@event.id, format: :xlsx) %><br>
  </p>

  <strong>Lisää ajat tiedostosta</strong><br>
  <%= form_tag import_file_path, multipart:true, method: :put do %>
    <%= file_field_tag :file %>
    <%= submit_tag 'Lähetä tiedosto', :class => "btn btn-primary"  %>
  <% end %>
  <br />
  <%= link_to 'Laske kilpailijoiden pisteet', calculate_points_path(@event.id), method:'post', :class => 'btn btn-primary' %>
  </p>
  <script type="text/javascript">
      $(document).ready(function () {
                  $.extend($.tablesorter.themes.bootstrap, {
                      // these classes are added to the table. To see other table classes available,
                      // look here: http://twitter.github.com/bootstrap/base-css.html#tables
                      table      : 'table table-bordered',
                      caption    : 'caption',
                      header     : 'bootstrap-header', // give the header a gradient background
                      footerRow  : '',
                      footerCells: '',
                      icons      : '', // add "icon-white" to make them white; this icon class is added to the <i> in the header
                      sortNone   : 'bootstrap-icon-unsorted',
                      sortAsc    : 'icon-chevron-up glyphicon glyphicon-chevron-up',     // includes classes for Bootstrap v2 & v3
                      sortDesc   : 'icon-chevron-down glyphicon glyphicon-chevron-down', // includes classes for Bootstrap v2 & v3
                      active     : '', // applied when column is sorted
                      hover      : '', // use custom css here - bootstrap class may not override it
                      filterRow  : '', // filter row class
                      even       : '', // odd row zebra striping
                      odd        : ''  // even row zebra striping
                  });

                  $("#eventparticipants").tablesorter({
                      // headers: {2: {sorter:false}, 3: {sorter:false}, 4: {sorter:false}},
                      theme: "bootstrap",
                      headerTemplate: '{content} {icon}',
                      widgets: [ "uitheme", "filter" ]
                  });
              }
      );
  </script>
</div>

app/views/enrollments/show_enrollments_for_event.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Osallistujan nimi</Data></Cell>
        <Cell><Data ss:Type="String">Osallistujan sähköposti</Data></Cell>
        <Cell><Data ss:Type="String">Osallistujan kk-numero</Data></Cell>
        <% @event.event_attributes.each do |attr| %>
        <Cell><Data ss:Type="String"><%= attr.name %></Data></Cell>
        <% end %>
      </Row>
      <% @event.participants.each do |user| %>
          <Row>
            <Cell><Data ss:Type="String"><%= user.first_name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= user.last_name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= user.kk_number %></Data></Cell>
            <% user.get_enrollment_data_for_event(@event.id).each do |data| %>
            <Cell><Data ss:Type="String"><%= data.value %></Data></Cell>
            <% end %>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>